# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'PMSPolicyholderV4.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from reportlab.pdfgen import canvas
from reportlab.lib.pagesizes import A4
from datetime import date


class Ui_MainWindow(object):

        def GenerateTermOfAdhesion(self):
                self.cnv = canvas.Canvas(f'{self.lineEdit_name.text()} - {self.label_playntype.text()}.pdf')

                # INSERT BARRIERS LOGO:
                self.cnv.drawImage(r'barrier_title_top.png',x=-20,y=780,width=600,height=50)
                self.cnv.drawImage(r'barrier_title_down.png',x=10,y=10,width=600,height=50)

                # INSERT TITLE AND PLAIN TYPE:
                self.cnv.drawImage(r'title_and_plain.png',x=200,y=710,width=300,height=50)

                #INSERT PLAIN NAME:
                self.cnv.drawString(x=260,y=720,text='OURO',mode=1)

                #ISNERT LOGO
                self.cnv.drawImage(r'logomp313x300.png',x=70,y=680,width=120,height=100)

                #INSERT COMPANY DATA:
                self.cnv.drawImage(r'company_data.png',x=70,y=590,width=475,height=100)
                                #COMPANY DATA
                self.cnv.drawString(x=165,y=657, text='MAXIMA PROTEÇÃO VEÍCULAR')
                self.cnv.drawString(x=165,y=642, text='845.523.0001-52')
                self.cnv.drawString(x=165,y=627, text='RUA ANTENOR NAVARRO, 933, PRATA - CG')
                self.cnv.drawString(x=165,y=612, text='083 9 8800 3030')
                self.cnv.drawString(x=165,y=597, text='083 9 8800 3055')    

                #INSERT POLICYHOLDER DATA:
                self.cnv.drawImage(r'client_data_and_adress.png',x=70,y=370,width=475,height=220)
                                #POLICIYHOLDER DATA
                self.cnv.drawString(x=165,y=552, text='SERGIO DOS SANTOS LIMA')
                self.cnv.drawString(x=165,y=537, text='088.749.844-21')
                self.cnv.drawString(x=165,y=523, text='3543976')
                self.cnv.drawString(x=165,y=509, text='083 9 96697578')
                self.cnv.drawString(x=165,y=494, text='083 9 65652321')  
                                #ADRESS:
                self.cnv.drawString(x=165,y=466, text='RUA ANGELA DE ALBUQUERQUE RAMOS')
                self.cnv.drawString(x=165,y=452, text='196')
                self.cnv.drawString(x=165,y=438, text='CASA')
                self.cnv.drawString(x=165,y=422, text='Malvinas')
                self.cnv.drawString(x=165,y=408, text='Campina Grande')
                self.cnv.drawString(x=165,y=393, text='85432-726')
                self.cnv.drawString(x=165,y=379, text='PB')


                #INSERT VECHICLE, COVERAGE AND FINANCE DATA:
                self.cnv.drawImage(r'vehicle_coverage_finance.png',x=70,y=175,width=475,height=200)
                                #VEHICLE DATA:
                self.cnv.drawString(x=175,y=340,  text='CHEVROLET')
                self.cnv.drawString(x=175,y=325,  text='CELTA 1.0')
                self.cnv.drawString(x=175,y=310,  text='MNO-7458')
                self.cnv.drawString(x=175,y=292,  text='PRETA')
                self.cnv.drawString(x=175,y=277,  text='2017')
                self.cnv.drawString(x=175,y=262,  text='BGK44A2S556SAS45745')
                self.cnv.drawString(x=175,y=245,  text='52325412')
                self.cnv.drawString(x=175,y=230,  text='32.000,00')
                self.cnv.drawString(x=175,y=214,  text='784511-8')
                                #COVERAGE DATA:
                self.cnv.drawString(x=320,y=340,  text='MONITORAMENTO')
                self.cnv.drawString(x=320,y=325,  text='ROUBO')
                self.cnv.drawString(x=320,y=310,  text='FURTO')
                self.cnv.drawString(x=320,y=292,  text='PERDA TOTAL')
                self.cnv.drawString(x=320,y=277,  text='Colisão')
                self.cnv.drawString(x=320,y=262,  text='3 Reboques Gratuitos')
                self.cnv.drawString(x=320,y=245,  text='6 Reboques Gratuitos')
                self.cnv.drawString(x=320,y=230,  text='Reboque Ilimitado')
                self.cnv.drawString(x=320,y=214,  text='500 Km de Reboque')
                self.cnv.drawString(x=320,y=198,  text='Vidros em Geral')
                self.cnv.drawString(x=320,y=182,  text='Terceiros')
                                #FINANCE DATA:
                self.cnv.drawString(x=448,y=340,  text='R$ 175,00')

                #INSERT OBSSERVATIONS FIELD:
                self.cnv.drawImage('observations.png',x=70, y=62,width=473,height=110)
                self.cnv.drawString(x=77, y=148, text='Limite de 68 caracteres por linha')
                
                        # COVERAGE SELECTION
                if self.checkBox_monitoring.isChecked():
                        self.coverages.append(self.checkBox_monitoring.text())
                if self.checkBox_robbery.isChecked():
                        self.coverages.append(self.checkBox_robbery.text())
                if self.checkBox_theft.isChecked():
                        self.coverages.append(self.checkBox_theft.text())
                if self.checkBox_collision.isChecked():
                        self.coverages.append(self.checkBox_collision.text())
                if self.checkBox_pt.isChecked():
                        self.coverages.append(self.checkBox_pt.text())
                if self.checkBox_winch3.isChecked():
                        self.coverages.append(self.checkBox_winch3.text())
                if self.checkBox_winch6.isChecked():
                        self.coverages.append(self.checkBox_winch6.text())
                if self.checkBox_unlimited_winch.isChecked():
                        self.coverages.append(self.checkBox_unlimited_winch.text())
                if self.checkBox_winch500.isChecked():
                        self.coverages.append(self.checkBox_winch500.text())
                if self.checkBox_glasses.isChecked():
                        self.coverages.append(self.checkBox_glasses.text())
                if self.checkBox_others.isChecked():
                        self.coverages.append(self.checkBox_others.text())

                #space_x = 60
                #space_y = 280
                #for coverage in self.coverages:
                #        self.cnv.drawString(space_x,space_y,coverage)
                #        space_y -= 12

                #INSERT DATE
                day = date.today().day
                month = date.today().month
                year = date.today().year

                month_current = str()
                if month == 1:
                        month_current = 'JANEIRO'
                elif month == 2:
                        month_current = 'FEVEREIRO'
                elif month == 3:
                        month_current = 'MARCO'
                elif month == 4:
                        month_current = 'ABRIL'
                elif month == 5:
                        month_current = 'MAIO'
                elif month == 6:
                        month_current = 'JUNHO'
                elif month == 7:
                        month_current = 'JULHO'
                elif month == 8:
                        month_current = 'AGOSTO'
                elif month == 9:
                        month_current = 'SETEMBRO'
                elif month == 10:
                        month_current = 'OUTUBRO'
                elif month == 11:
                        month_current = 'NOVEMBRO'
                elif month == 12:
                        month_current = 'DEZEMBRO'
                self.cnv.drawString(x=408,y=52,text=f'{day} de {month_current} de {year}')


                #CREATE PDF
                self.cnv.save()

        def setupUi(self, MainWindow):
                MainWindow.setObjectName("MainWindow")
                MainWindow.resize(1424, 536)
                icon = QtGui.QIcon()
                icon.addPixmap(QtGui.QPixmap("Images/pms_icon-16x16.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
                MainWindow.setWindowIcon(icon)
                MainWindow.setStyleSheet("QScrollBar:vertical{\n"
        "    border: none;\n"
        "    background-color: rgb(170, 255, 255);\n"
        "    width:14px;\n"
        "    margin: 15px 0 15px 0;\n"
        "    border-radius: 0px;\n"
        "}\n"
        "QScrollBar::handle:vertical{\n"
        "    background-color: rgb(50, 200, 255);\n"
        "    mini-height: 30px;\n"
        "    border-radius: 7px;\n"
        "}\n"
        "QScrollBar::handle:vertical:hover{\n"
        "    background-color: rgb(70, 220, 255);\n"
        "}\n"
        "QScrollBar::handle:vertical:pressed{\n"
        "    background-color: rgb(30, 180, 255);\n"
        "}\n"
        "QScrollBar::sub-line:vertical{\n"
        "    border: none;\n"
        "    background-color: rgb(50, 200, 255);\n"
        "    height: 15px;\n"
        "    border-top-left-radius: 7px;\n"
        "    border-top-right-radius: 7px; \n"
        "    subcontrol-posiiton: top;\n"
        "    subcontrol-origin: margin;\n"
        "}\n"
        "QScrollBar::sub-line:vertical:hover{\n"
        "    background-color: rgb(70, 220, 255);\n"
        "}\n"
        "QScrollBar::sub-line:vertical:pressed{\n"
        "    background-color: rgb(30, 180, 255);\n"
        "}\n"
        "QScrollBar::add-line:vertical{\n"
        "    border: none;\n"
        "    background-color: rgb(50, 200, 255);\n"
        "    height: 15px;\n"
        "    border-bottom-left-radius: 7px;\n"
        "    border-botton-right-radius: 7px;\n"
        "    subcontrol-posiiton: botton;\n"
        "    subcontrol-origin: margin;\n"
        "}\n"
        "QScrollBar::add-line:vertical:hover{\n"
        "    background-color: rgb(70, 220, 255);\n"
        "}\n"
        "QScrollBar::add-line:vertical:pressed{\n"
        "    background-color: rgb(30, 180, 255);\n"
        "}\n"
        "\n"
        "QScrollBar::up-arrow:vertical, QScrollBar::down-arrow:vertical{\n"
        "    background: none;\n"
        "}\n"
        "QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical{\n"
        "    background: none;\n"
        "}\n"
        "\n"
        "/*HORIZONTAL SCROW BAR*/\n"
        "\n"
        "QScrollBar:horizontal{\n"
        "    border: none;\n"
        "    background-color: rgb(170, 255, 255);\n"
        "    heigth:14px;\n"
        "    border-radius: 0px;\n"
        "}\n"
        "QScrollBar::handle:horizontal{\n"
        "    background-color: rgb(50, 200, 255);\n"
        "    mini-height: 30px;\n"
        "    border-radius: 7px;\n"
        "}\n"
        "QScrollBar::handle:horizontal:hover{\n"
        "    background-color: rgb(70, 220, 255);\n"
        "}\n"
        "QScrollBar::handle:horizontal:pressed{\n"
        "    background-color: rgb(30, 180, 255);\n"
        "}\n"
        "QScrollBar::sub-line:horizontal{\n"
        "    border: none;\n"
        "    background-color: rgb(50, 200, 255);\n"
        "    width: 15px;\n"
        "    border-top-left-radius: 7px;\n"
        "    border-top-right-radius: 7px; \n"
        "    subcontrol-posiiton: top;\n"
        "    subcontrol-origin: margin;\n"
        "}\n"
        "QScrollBar::sub-line:horizontal:hover{\n"
        "    background-color: rgb(70, 220, 255);\n"
        "}\n"
        "QScrollBar::sub-line:horizontal:pressed{\n"
        "    background-color: rgb(30, 180, 255);\n"
        "}\n"
        "QScrollBar::add-line:horizontal{\n"
        "    border: none;\n"
        "    background-color: rgb(50, 200, 255);\n"
        "    width: 15px;\n"
        "    border-bottom-left-radius: 7px;\n"
        "    border-botton-right-radius: 7px;\n"
        "    subcontrol-posiiton: botton;\n"
        "    subcontrol-origin: margin;\n"
        "}\n"
        "")
                self.centralwidget = QtWidgets.QWidget(MainWindow)
                self.centralwidget.setObjectName("centralwidget")
                self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
                self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
                self.horizontalLayout.setSpacing(0)
                self.horizontalLayout.setObjectName("horizontalLayout")
                self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
                self.scrollArea.setStyleSheet("QScrollBar:vertical{\n"
        "    border: none;\n"
        "    background-color: rgb(170, 255, 255);\n"
        "}")
                self.scrollArea.setFrameShape(QtWidgets.QFrame.NoFrame)
                self.scrollArea.setWidgetResizable(True)
                self.scrollArea.setObjectName("scrollArea")
                self.scrollAreaWidgetContents = QtWidgets.QWidget()
                self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, -76, 1410, 700))
                self.scrollAreaWidgetContents.setStyleSheet("")
                self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
                self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.scrollAreaWidgetContents)
                self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
                self.horizontalLayout_2.setSpacing(0)
                self.horizontalLayout_2.setObjectName("horizontalLayout_2")
                self.frame_fill_fiedls = QtWidgets.QFrame(self.scrollAreaWidgetContents)
                self.frame_fill_fiedls.setMinimumSize(QtCore.QSize(700, 700))
                self.frame_fill_fiedls.setStyleSheet("background-color: rgb(170, 255, 255);")
                self.frame_fill_fiedls.setFrameShape(QtWidgets.QFrame.StyledPanel)
                self.frame_fill_fiedls.setFrameShadow(QtWidgets.QFrame.Raised)
                self.frame_fill_fiedls.setObjectName("frame_fill_fiedls")
                self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_fill_fiedls)
                self.horizontalLayout_3.setContentsMargins(9, 9, 9, 9)
                self.horizontalLayout_3.setSpacing(9)
                self.horizontalLayout_3.setObjectName("horizontalLayout_3")
                self.frame_logo_name = QtWidgets.QFrame(self.frame_fill_fiedls)
                self.frame_logo_name.setMinimumSize(QtCore.QSize(255, 200))
                self.frame_logo_name.setMaximumSize(QtCore.QSize(16777215, 16777215))
                self.frame_logo_name.setStyleSheet("QFrame{\n"
        "    image: url(:/backgrounds/Images/pms_logo1-200x144.png);\n"
        "    image-position: top 2px;\n"
        "    border: no-border;\n"
        "}")
                self.frame_logo_name.setFrameShape(QtWidgets.QFrame.StyledPanel)
                self.frame_logo_name.setFrameShadow(QtWidgets.QFrame.Raised)
                self.frame_logo_name.setObjectName("frame_logo_name")
                self.textBrowser_logo_name = QtWidgets.QTextBrowser(self.frame_logo_name)
                self.textBrowser_logo_name.setGeometry(QtCore.QRect(10, 150, 281, 41))
                self.textBrowser_logo_name.setObjectName("textBrowser_logo_name")
                self.horizontalLayout_3.addWidget(self.frame_logo_name)
                self.frame_coverages_outside = QtWidgets.QFrame(self.frame_fill_fiedls)
                self.frame_coverages_outside.setMinimumSize(QtCore.QSize(150, 0))
                self.frame_coverages_outside.setMaximumSize(QtCore.QSize(300, 16777215))
                self.frame_coverages_outside.setStyleSheet("background-image: url(:/backgrounds/Images/background-blue-1715x980.jpg);\n"
        "border-radius: 8px;")
                self.frame_coverages_outside.setFrameShape(QtWidgets.QFrame.StyledPanel)
                self.frame_coverages_outside.setFrameShadow(QtWidgets.QFrame.Raised)
                self.frame_coverages_outside.setObjectName("frame_coverages_outside")
                self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_coverages_outside)
                self.verticalLayout_4.setObjectName("verticalLayout_4")
                self.frame_coverages_inside = QtWidgets.QFrame(self.frame_coverages_outside)
                self.frame_coverages_inside.setMinimumSize(QtCore.QSize(50, 50))
                self.frame_coverages_inside.setStyleSheet("QFrame{\n"
        "    border: 2px solid rgb(36, 183, 253);\n"
        "    border-radius: 8px;\n"
        "}")
                self.frame_coverages_inside.setFrameShape(QtWidgets.QFrame.StyledPanel)
                self.frame_coverages_inside.setFrameShadow(QtWidgets.QFrame.Raised)
                self.frame_coverages_inside.setObjectName("frame_coverages_inside")
                self.verticalLayout = QtWidgets.QVBoxLayout(self.frame_coverages_inside)
                self.verticalLayout.setObjectName("verticalLayout")
                self.label_coverage = QtWidgets.QLabel(self.frame_coverages_inside)
                self.label_coverage.setMinimumSize(QtCore.QSize(0, 0))
                self.label_coverage.setMaximumSize(QtCore.QSize(16777215, 20))
                font = QtGui.QFont()
                font.setFamily("Segoe UI")
                font.setPointSize(10)
                font.setBold(True)
                font.setWeight(75)
                self.label_coverage.setFont(font)
                self.label_coverage.setStyleSheet("border: no-border")
                self.label_coverage.setAlignment(QtCore.Qt.AlignCenter)
                self.label_coverage.setObjectName("label_coverage")
                self.verticalLayout.addWidget(self.label_coverage)
                self.checkBox_monitoring = QtWidgets.QCheckBox(self.frame_coverages_inside)
                font = QtGui.QFont()
                font.setFamily("Segoe UI")
                font.setBold(True)
                font.setWeight(75)
                self.checkBox_monitoring.setFont(font)
                self.checkBox_monitoring.setStyleSheet("QCheckBox{\n"
        "    background-color: rgb(92, 230, 255);\n"
        "}\n"
        "QCheckBox:hover{\n"
        "    color: rgb(0, 0, 255);\n"
        "}")
                self.checkBox_monitoring.setObjectName("checkBox_monitoring")
                self.verticalLayout.addWidget(self.checkBox_monitoring)
                self.checkBox_robbery = QtWidgets.QCheckBox(self.frame_coverages_inside)
                font = QtGui.QFont()
                font.setFamily("Segoe UI")
                font.setBold(True)
                font.setWeight(75)
                self.checkBox_robbery.setFont(font)
                self.checkBox_robbery.setStyleSheet("QCheckBox{\n"
        "    background-color: rgb(92, 230, 255);\n"
        "}\n"
        "QCheckBox:hover{\n"
        "    color: rgb(0, 0, 255);\n"
        "}")
                self.checkBox_robbery.setObjectName("checkBox_robbery")
                self.verticalLayout.addWidget(self.checkBox_robbery)
                self.checkBox_theft = QtWidgets.QCheckBox(self.frame_coverages_inside)
                font = QtGui.QFont()
                font.setFamily("Segoe UI")
                font.setBold(True)
                font.setWeight(75)
                self.checkBox_theft.setFont(font)
                self.checkBox_theft.setStyleSheet("QCheckBox{\n"
        "    background-color: rgb(92, 230, 255);\n"
        "}\n"
        "QCheckBox:hover{\n"
        "    color: rgb(0, 0, 255);\n"
        "}")
                self.checkBox_theft.setObjectName("checkBox_theft")
                self.verticalLayout.addWidget(self.checkBox_theft)
                self.checkBox_pt = QtWidgets.QCheckBox(self.frame_coverages_inside)
                font = QtGui.QFont()
                font.setFamily("Segoe UI")
                font.setBold(True)
                font.setWeight(75)
                self.checkBox_pt.setFont(font)
                self.checkBox_pt.setStyleSheet("QCheckBox{\n"
        "    background-color: rgb(92, 230, 255);\n"
        "}\n"
        "QCheckBox:hover{\n"
        "    color: rgb(0, 0, 255);\n"
        "}")
                self.checkBox_pt.setObjectName("checkBox_pt")
                self.verticalLayout.addWidget(self.checkBox_pt)
                self.checkBox_collision = QtWidgets.QCheckBox(self.frame_coverages_inside)
                font = QtGui.QFont()
                font.setFamily("Segoe UI")
                font.setBold(True)
                font.setWeight(75)
                self.checkBox_collision.setFont(font)
                self.checkBox_collision.setStyleSheet("QCheckBox{\n"
        "    background-color: rgb(92, 230, 255);\n"
        "}\n"
        "QCheckBox:hover{\n"
        "    color: rgb(0, 0, 255);\n"
        "}")
                self.checkBox_collision.setObjectName("checkBox_collision")
                self.verticalLayout.addWidget(self.checkBox_collision)
                self.checkBox_winch3 = QtWidgets.QCheckBox(self.frame_coverages_inside)
                font = QtGui.QFont()
                font.setFamily("Segoe UI")
                font.setBold(True)
                font.setWeight(75)
                self.checkBox_winch3.setFont(font)
                self.checkBox_winch3.setStyleSheet("QCheckBox{\n"
        "    background-color: rgb(92, 230, 255);\n"
        "}\n"
        "QCheckBox:hover{\n"
        "    color: rgb(0, 0, 255);\n"
        "}")
                self.checkBox_winch3.setObjectName("checkBox_winch3")
                self.verticalLayout.addWidget(self.checkBox_winch3)
                self.checkBox_winch6 = QtWidgets.QCheckBox(self.frame_coverages_inside)
                font = QtGui.QFont()
                font.setFamily("Segoe UI")
                font.setBold(True)
                font.setWeight(75)
                self.checkBox_winch6.setFont(font)
                self.checkBox_winch6.setStyleSheet("QCheckBox{\n"
        "    background-color: rgb(92, 230, 255);\n"
        "}\n"
        "QCheckBox:hover{\n"
        "    color: rgb(0, 0, 255);\n"
        "}")
                self.checkBox_winch6.setObjectName("checkBox_winch6")
                self.verticalLayout.addWidget(self.checkBox_winch6)
                self.checkBox_unlimited_winch = QtWidgets.QCheckBox(self.frame_coverages_inside)
                font = QtGui.QFont()
                font.setFamily("Segoe UI")
                font.setBold(True)
                font.setWeight(75)
                self.checkBox_unlimited_winch.setFont(font)
                self.checkBox_unlimited_winch.setStyleSheet("QCheckBox{\n"
        "    background-color: rgb(92, 230, 255);\n"
        "}\n"
        "QCheckBox:hover{\n"
        "    color: rgb(0, 0, 255);\n"
        "}")
                self.checkBox_unlimited_winch.setObjectName("checkBox_unlimited_winch")
                self.verticalLayout.addWidget(self.checkBox_unlimited_winch)
                self.checkBox_winch500 = QtWidgets.QCheckBox(self.frame_coverages_inside)
                font = QtGui.QFont()
                font.setFamily("Segoe UI")
                font.setBold(True)
                font.setWeight(75)
                self.checkBox_winch500.setFont(font)
                self.checkBox_winch500.setStyleSheet("QCheckBox{\n"
        "    background-color: rgb(92, 230, 255);\n"
        "}\n"
        "QCheckBox:hover{\n"
        "    color: rgb(0, 0, 255);\n"
        "}")
                self.checkBox_winch500.setObjectName("checkBox_winch500")
                self.verticalLayout.addWidget(self.checkBox_winch500)
                self.checkBox_glasses = QtWidgets.QCheckBox(self.frame_coverages_inside)
                font = QtGui.QFont()
                font.setFamily("Segoe UI")
                font.setBold(True)
                font.setWeight(75)
                self.checkBox_glasses.setFont(font)
                self.checkBox_glasses.setStyleSheet("QCheckBox{\n"
        "    background-color: rgb(92, 230, 255);\n"
        "}\n"
        "QCheckBox:hover{\n"
        "    color: rgb(0, 0, 255);\n"
        "}")
                self.checkBox_glasses.setObjectName("checkBox_glasses")
                self.verticalLayout.addWidget(self.checkBox_glasses)
                self.checkBox_others = QtWidgets.QCheckBox(self.frame_coverages_inside)
                font = QtGui.QFont()
                font.setFamily("Segoe UI")
                font.setBold(True)
                font.setWeight(75)
                self.checkBox_others.setFont(font)
                self.checkBox_others.setStyleSheet("QCheckBox{\n"
        "    background-color: rgb(92, 230, 255);\n"
        "}\n"
        "QCheckBox:hover{\n"
        "    color: rgb(0, 0, 255);\n"
        "}")
                self.checkBox_others.setObjectName("checkBox_others")
                self.verticalLayout.addWidget(self.checkBox_others)
                self.verticalLayout_4.addWidget(self.frame_coverages_inside)
                self.horizontalLayout_3.addWidget(self.frame_coverages_outside)
                self.frame_client_data_outside = QtWidgets.QFrame(self.frame_fill_fiedls)
                self.frame_client_data_outside.setMinimumSize(QtCore.QSize(150, 0))
                self.frame_client_data_outside.setMaximumSize(QtCore.QSize(300, 16777215))
                self.frame_client_data_outside.setStyleSheet("background-image: url(:/backgrounds/Images/background-blue-1715x980.jpg);\n"
        "border-radius: 8px;")
                self.frame_client_data_outside.setFrameShape(QtWidgets.QFrame.StyledPanel)
                self.frame_client_data_outside.setFrameShadow(QtWidgets.QFrame.Raised)
                self.frame_client_data_outside.setObjectName("frame_client_data_outside")
                self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_client_data_outside)
                self.verticalLayout_2.setObjectName("verticalLayout_2")
                self.frame_client_data_inside = QtWidgets.QFrame(self.frame_client_data_outside)
                self.frame_client_data_inside.setMinimumSize(QtCore.QSize(150, 50))
                self.frame_client_data_inside.setStyleSheet("QFrame{\n"
        "    border: 2px solid rgb(36, 183, 253);\n"
        "    border-radius: 8px;\n"
        "}")
                self.frame_client_data_inside.setFrameShape(QtWidgets.QFrame.StyledPanel)
                self.frame_client_data_inside.setFrameShadow(QtWidgets.QFrame.Raised)
                self.frame_client_data_inside.setObjectName("frame_client_data_inside")
                self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame_client_data_inside)
                self.verticalLayout_5.setObjectName("verticalLayout_5")
                self.label_clientdata = QtWidgets.QLabel(self.frame_client_data_inside)
                self.label_clientdata.setMinimumSize(QtCore.QSize(0, 0))
                self.label_clientdata.setMaximumSize(QtCore.QSize(16777215, 20))
                font = QtGui.QFont()
                font.setFamily("Segoe UI")
                font.setPointSize(10)
                font.setBold(True)
                font.setWeight(75)
                self.label_clientdata.setFont(font)
                self.label_clientdata.setStyleSheet("border:no")
                self.label_clientdata.setAlignment(QtCore.Qt.AlignCenter)
                self.label_clientdata.setObjectName("label_clientdata")
                self.verticalLayout_5.addWidget(self.label_clientdata)
                self.lineEdit_name = QtWidgets.QLineEdit(self.frame_client_data_inside)
                self.lineEdit_name.setStyleSheet("QLineEdit{\n"
        "    \n"
        "    background-color: rgb(148, 148, 148);\n"
        "    border: 1px solid rgb(10,10,10);\n"
        "    border-radius: 5px;\n"
        "    padding: 2px;\n"
        "}\n"
        "QLineEdit:hover{\n"
        "    border: 1px solid rgb(150,150,150);\n"
        "}\n"
        "QLineEdit:focus{\n"
        "    border: 2px solid rgb(100, 100, 255);\n"
        "}")
                self.lineEdit_name.setObjectName("lineEdit_name")
                self.verticalLayout_5.addWidget(self.lineEdit_name)
                self.lineEdit_cpf = QtWidgets.QLineEdit(self.frame_client_data_inside)
                self.lineEdit_cpf.setStyleSheet("QLineEdit{\n"
        "    \n"
        "    background-color: rgb(148, 148, 148);\n"
        "    border: 1px solid rgb(10,10,10);\n"
        "    border-radius: 5px;\n"
        "    padding: 2px;\n"
        "}\n"
        "QLineEdit:hover{\n"
        "    border: 1px solid rgb(150,150,150);\n"
        "}\n"
        "QLineEdit:focus{\n"
        "    border: 2px solid rgb(100, 100, 255);\n"
        "}")
                self.lineEdit_cpf.setObjectName("lineEdit_cpf")
                self.verticalLayout_5.addWidget(self.lineEdit_cpf)
                self.lineEdit_rg = QtWidgets.QLineEdit(self.frame_client_data_inside)
                self.lineEdit_rg.setStyleSheet("QLineEdit{\n"
        "    \n"
        "    background-color: rgb(148, 148, 148);\n"
        "    border: 1px solid rgb(10,10,10);\n"
        "    border-radius: 5px;\n"
        "    padding: 2px;\n"
        "}\n"
        "QLineEdit:hover{\n"
        "    border: 1px solid rgb(150,150,150);\n"
        "}\n"
        "QLineEdit:focus{\n"
        "    border: 2px solid rgb(100, 100, 255);\n"
        "}")
                self.lineEdit_rg.setObjectName("lineEdit_rg")
                self.verticalLayout_5.addWidget(self.lineEdit_rg)
                self.lineEdit_phone1 = QtWidgets.QLineEdit(self.frame_client_data_inside)
                self.lineEdit_phone1.setStyleSheet("QLineEdit{\n"
        "    \n"
        "    background-color: rgb(148, 148, 148);\n"
        "    border: 1px solid rgb(10,10,10);\n"
        "    border-radius: 5px;\n"
        "    padding: 2px;\n"
        "}\n"
        "QLineEdit:hover{\n"
        "    border: 1px solid rgb(150,150,150);\n"
        "}\n"
        "QLineEdit:focus{\n"
        "    border: 2px solid rgb(100, 100, 255);\n"
        "}")
                self.lineEdit_phone1.setObjectName("lineEdit_phone1")
                self.verticalLayout_5.addWidget(self.lineEdit_phone1)
                self.lineEdit_phone2 = QtWidgets.QLineEdit(self.frame_client_data_inside)
                self.lineEdit_phone2.setStyleSheet("QLineEdit{\n"
        "    \n"
        "    background-color: rgb(148, 148, 148);\n"
        "    border: 1px solid rgb(10,10,10);\n"
        "    border-radius: 5px;\n"
        "    padding: 2px;\n"
        "}\n"
        "QLineEdit:hover{\n"
        "    border: 1px solid rgb(150,150,150);\n"
        "}\n"
        "QLineEdit:focus{\n"
        "    border: 2px solid rgb(100, 100, 255);\n"
        "}")
                self.lineEdit_phone2.setObjectName("lineEdit_phone2")
                self.verticalLayout_5.addWidget(self.lineEdit_phone2)
                self.label_adress = QtWidgets.QLabel(self.frame_client_data_inside)
                self.label_adress.setMinimumSize(QtCore.QSize(0, 0))
                self.label_adress.setMaximumSize(QtCore.QSize(16777215, 20))
                font = QtGui.QFont()
                font.setFamily("Segoe UI")
                font.setPointSize(8)
                font.setBold(False)
                font.setWeight(50)
                self.label_adress.setFont(font)
                self.label_adress.setStyleSheet("border-color: rgb(36, 183, 253);")
                self.label_adress.setAlignment(QtCore.Qt.AlignCenter)
                self.label_adress.setObjectName("label_adress")
                self.verticalLayout_5.addWidget(self.label_adress)
                self.lineEdit_street = QtWidgets.QLineEdit(self.frame_client_data_inside)
                self.lineEdit_street.setStyleSheet("QLineEdit{\n"
        "    \n"
        "    background-color: rgb(148, 148, 148);\n"
        "    border: 1px solid rgb(10,10,10);\n"
        "    border-radius: 5px;\n"
        "    padding: 2px;\n"
        "}\n"
        "QLineEdit:hover{\n"
        "    border: 1px solid rgb(150,150,150);\n"
        "}\n"
        "QLineEdit:focus{\n"
        "    border: 2px solid rgb(100, 100, 255);\n"
        "}")
                self.lineEdit_street.setObjectName("lineEdit_street")
                self.verticalLayout_5.addWidget(self.lineEdit_street)
                self.lineEdit_number = QtWidgets.QLineEdit(self.frame_client_data_inside)
                self.lineEdit_number.setStyleSheet("QLineEdit{\n"
        "    \n"
        "    background-color: rgb(148, 148, 148);\n"
        "    border: 1px solid rgb(10,10,10);\n"
        "    border-radius: 5px;\n"
        "    padding: 2px;\n"
        "}\n"
        "QLineEdit:hover{\n"
        "    border: 1px solid rgb(150,150,150);\n"
        "}\n"
        "QLineEdit:focus{\n"
        "    border: 2px solid rgb(100, 100, 255);\n"
        "}")
                self.lineEdit_number.setObjectName("lineEdit_number")
                self.verticalLayout_5.addWidget(self.lineEdit_number)
                self.lineEdit_comp = QtWidgets.QLineEdit(self.frame_client_data_inside)
                self.lineEdit_comp.setStyleSheet("QLineEdit{\n"
        "    \n"
        "    background-color: rgb(148, 148, 148);\n"
        "    border: 1px solid rgb(10,10,10);\n"
        "    border-radius: 5px;\n"
        "    padding: 2px;\n"
        "}\n"
        "QLineEdit:hover{\n"
        "    border: 1px solid rgb(150,150,150);\n"
        "}\n"
        "QLineEdit:focus{\n"
        "    border: 2px solid rgb(100, 100, 255);\n"
        "}")
                self.lineEdit_comp.setObjectName("lineEdit_comp")
                self.verticalLayout_5.addWidget(self.lineEdit_comp)
                self.lineEdit_neghbordhood = QtWidgets.QLineEdit(self.frame_client_data_inside)
                self.lineEdit_neghbordhood.setStyleSheet("QLineEdit{\n"
        "    \n"
        "    background-color: rgb(148, 148, 148);\n"
        "    border: 1px solid rgb(10,10,10);\n"
        "    border-radius: 5px;\n"
        "    padding: 2px;\n"
        "}\n"
        "QLineEdit:hover{\n"
        "    border: 1px solid rgb(150,150,150);\n"
        "}\n"
        "QLineEdit:focus{\n"
        "    border: 2px solid rgb(100, 100, 255);\n"
        "}")
                self.lineEdit_neghbordhood.setObjectName("lineEdit_neghbordhood")
                self.verticalLayout_5.addWidget(self.lineEdit_neghbordhood)
                self.lineEdit_city = QtWidgets.QLineEdit(self.frame_client_data_inside)
                self.lineEdit_city.setStyleSheet("QLineEdit{\n"
        "    \n"
        "    background-color: rgb(148, 148, 148);\n"
        "    border: 1px solid rgb(10,10,10);\n"
        "    border-radius: 5px;\n"
        "    padding: 2px;\n"
        "}\n"
        "QLineEdit:hover{\n"
        "    border: 1px solid rgb(150,150,150);\n"
        "}\n"
        "QLineEdit:focus{\n"
        "    border: 2px solid rgb(100, 100, 255);\n"
        "}")
                self.lineEdit_city.setObjectName("lineEdit_city")
                self.verticalLayout_5.addWidget(self.lineEdit_city)
                self.lineEdit_uf = QtWidgets.QLineEdit(self.frame_client_data_inside)
                self.lineEdit_uf.setStyleSheet("QLineEdit{\n"
        "    \n"
        "    background-color: rgb(148, 148, 148);\n"
        "    border: 1px solid rgb(10,10,10);\n"
        "    border-radius: 5px;\n"
        "    padding: 2px;\n"
        "}\n"
        "QLineEdit:hover{\n"
        "    border: 1px solid rgb(150,150,150);\n"
        "}\n"
        "QLineEdit:focus{\n"
        "    border: 2px solid rgb(100, 100, 255);\n"
        "}")
                self.lineEdit_uf.setObjectName("lineEdit_uf")
                self.verticalLayout_5.addWidget(self.lineEdit_uf)
                self.lineEdit_cep = QtWidgets.QLineEdit(self.frame_client_data_inside)
                self.lineEdit_cep.setStyleSheet("QLineEdit{\n"
        "    \n"
        "    background-color: rgb(148, 148, 148);\n"
        "    border: 1px solid rgb(10,10,10);\n"
        "    border-radius: 5px;\n"
        "    padding: 2px;\n"
        "}\n"
        "QLineEdit:hover{\n"
        "    border: 1px solid rgb(150,150,150);\n"
        "}\n"
        "QLineEdit:focus{\n"
        "    border: 2px solid rgb(100, 100, 255);\n"
        "}")
                self.lineEdit_cep.setObjectName("lineEdit_cep")
                self.verticalLayout_5.addWidget(self.lineEdit_cep)
                self.verticalLayout_2.addWidget(self.frame_client_data_inside)
                self.horizontalLayout_3.addWidget(self.frame_client_data_outside)
                self.frame_vehicle_pain_data_outside = QtWidgets.QFrame(self.frame_fill_fiedls)
                self.frame_vehicle_pain_data_outside.setMinimumSize(QtCore.QSize(0, 0))
                self.frame_vehicle_pain_data_outside.setMaximumSize(QtCore.QSize(300, 16777215))
                self.frame_vehicle_pain_data_outside.setStyleSheet("background-image: url(:/backgrounds/Images/background-blue-1715x980.jpg);\n"
        "border-radius: 8px;")
                self.frame_vehicle_pain_data_outside.setFrameShape(QtWidgets.QFrame.StyledPanel)
                self.frame_vehicle_pain_data_outside.setFrameShadow(QtWidgets.QFrame.Raised)
                self.frame_vehicle_pain_data_outside.setObjectName("frame_vehicle_pain_data_outside")
                self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.frame_vehicle_pain_data_outside)
                self.verticalLayout_9.setObjectName("verticalLayout_9")
                self.frame_vehicle_plain_data_inside = QtWidgets.QFrame(self.frame_vehicle_pain_data_outside)
                self.frame_vehicle_plain_data_inside.setMinimumSize(QtCore.QSize(150, 50))
                self.frame_vehicle_plain_data_inside.setStyleSheet("QFrame{\n"
        "    border: 2px solid rgb(36, 183, 253);\n"
        "    border-radius: 8px;\n"
        "}")
                self.frame_vehicle_plain_data_inside.setFrameShape(QtWidgets.QFrame.StyledPanel)
                self.frame_vehicle_plain_data_inside.setFrameShadow(QtWidgets.QFrame.Raised)
                self.frame_vehicle_plain_data_inside.setObjectName("frame_vehicle_plain_data_inside")
                self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_vehicle_plain_data_inside)
                self.verticalLayout_3.setObjectName("verticalLayout_3")
                self.label_vehicle = QtWidgets.QLabel(self.frame_vehicle_plain_data_inside)
                self.label_vehicle.setMinimumSize(QtCore.QSize(0, 0))
                self.label_vehicle.setMaximumSize(QtCore.QSize(16777215, 20))
                font = QtGui.QFont()
                font.setFamily("Segoe UI")
                font.setPointSize(10)
                font.setBold(True)
                font.setWeight(75)
                self.label_vehicle.setFont(font)
                self.label_vehicle.setStyleSheet("border:no")
                self.label_vehicle.setAlignment(QtCore.Qt.AlignCenter)
                self.label_vehicle.setObjectName("label_vehicle")
                self.verticalLayout_3.addWidget(self.label_vehicle)
                self.lineEdit_assembler = QtWidgets.QLineEdit(self.frame_vehicle_plain_data_inside)
                self.lineEdit_assembler.setStyleSheet("QLineEdit{\n"
        "    \n"
        "    background-color: rgb(148, 148, 148);\n"
        "    border: 1px solid rgb(10,10,10);\n"
        "    border-radius: 5px;\n"
        "    padding: 2px;\n"
        "}\n"
        "QLineEdit:hover{\n"
        "    border: 1px solid rgb(150,150,150);\n"
        "}\n"
        "QLineEdit:focus{\n"
        "    border: 2px solid rgb(100, 100, 255);\n"
        "}")
                self.lineEdit_assembler.setObjectName("lineEdit_assembler")
                self.verticalLayout_3.addWidget(self.lineEdit_assembler)
                self.lineEdit_model = QtWidgets.QLineEdit(self.frame_vehicle_plain_data_inside)
                self.lineEdit_model.setStyleSheet("QLineEdit{\n"
        "    \n"
        "    background-color: rgb(148, 148, 148);\n"
        "    border: 1px solid rgb(10,10,10);\n"
        "    border-radius: 5px;\n"
        "    padding: 2px;\n"
        "}\n"
        "QLineEdit:hover{\n"
        "    border: 1px solid rgb(150,150,150);\n"
        "}\n"
        "QLineEdit:focus{\n"
        "    border: 2px solid rgb(100, 100, 255);\n"
        "}")
                self.lineEdit_model.setObjectName("lineEdit_model")
                self.verticalLayout_3.addWidget(self.lineEdit_model)
                self.lineEdit_plate = QtWidgets.QLineEdit(self.frame_vehicle_plain_data_inside)
                self.lineEdit_plate.setStyleSheet("QLineEdit{\n"
        "    \n"
        "    background-color: rgb(148, 148, 148);\n"
        "    border: 1px solid rgb(10,10,10);\n"
        "    border-radius: 5px;\n"
        "    padding: 2px;\n"
        "}\n"
        "QLineEdit:hover{\n"
        "    border: 1px solid rgb(150,150,150);\n"
        "}\n"
        "QLineEdit:focus{\n"
        "    border: 2px solid rgb(100, 100, 255);\n"
        "}")
                self.lineEdit_plate.setObjectName("lineEdit_plate")
                self.verticalLayout_3.addWidget(self.lineEdit_plate)
                self.lineEdit_color = QtWidgets.QLineEdit(self.frame_vehicle_plain_data_inside)
                self.lineEdit_color.setStyleSheet("QLineEdit{\n"
        "    \n"
        "    background-color: rgb(148, 148, 148);\n"
        "    border: 1px solid rgb(10,10,10);\n"
        "    border-radius: 5px;\n"
        "    padding: 2px;\n"
        "}\n"
        "QLineEdit:hover{\n"
        "    border: 1px solid rgb(150,150,150);\n"
        "}\n"
        "QLineEdit:focus{\n"
        "    border: 2px solid rgb(100, 100, 255);\n"
        "}")
                self.lineEdit_color.setObjectName("lineEdit_color")
                self.verticalLayout_3.addWidget(self.lineEdit_color)
                self.lineEdit_year = QtWidgets.QLineEdit(self.frame_vehicle_plain_data_inside)
                self.lineEdit_year.setStyleSheet("QLineEdit{\n"
        "    \n"
        "    background-color: rgb(148, 148, 148);\n"
        "    border: 1px solid rgb(10,10,10);\n"
        "    border-radius: 5px;\n"
        "    padding: 2px;\n"
        "}\n"
        "QLineEdit:hover{\n"
        "    border: 1px solid rgb(150,150,150);\n"
        "}\n"
        "QLineEdit:focus{\n"
        "    border: 2px solid rgb(100, 100, 255);\n"
        "}")
                self.lineEdit_year.setObjectName("lineEdit_year")
                self.verticalLayout_3.addWidget(self.lineEdit_year)
                self.lineEdit_chassis = QtWidgets.QLineEdit(self.frame_vehicle_plain_data_inside)
                self.lineEdit_chassis.setStyleSheet("QLineEdit{\n"
        "    \n"
        "    background-color: rgb(148, 148, 148);\n"
        "    border: 1px solid rgb(10,10,10);\n"
        "    border-radius: 5px;\n"
        "    padding: 2px;\n"
        "}\n"
        "QLineEdit:hover{\n"
        "    border: 1px solid rgb(150,150,150);\n"
        "}\n"
        "QLineEdit:focus{\n"
        "    border: 2px solid rgb(100, 100, 255);\n"
        "}")
                self.lineEdit_chassis.setObjectName("lineEdit_chassis")
                self.verticalLayout_3.addWidget(self.lineEdit_chassis)
                self.lineEdit_renavam = QtWidgets.QLineEdit(self.frame_vehicle_plain_data_inside)
                self.lineEdit_renavam.setStyleSheet("QLineEdit{\n"
        "    \n"
        "    background-color: rgb(148, 148, 148);\n"
        "    border: 1px solid rgb(10,10,10);\n"
        "    border-radius: 5px;\n"
        "    padding: 2px;\n"
        "}\n"
        "QLineEdit:hover{\n"
        "    border: 1px solid rgb(150,150,150);\n"
        "}\n"
        "QLineEdit:focus{\n"
        "    border: 2px solid rgb(100, 100, 255);\n"
        "}")
                self.lineEdit_renavam.setObjectName("lineEdit_renavam")
                self.verticalLayout_3.addWidget(self.lineEdit_renavam)
                self.lineEdit_fipe_value = QtWidgets.QLineEdit(self.frame_vehicle_plain_data_inside)
                self.lineEdit_fipe_value.setStyleSheet("QLineEdit{\n"
        "    \n"
        "    background-color: rgb(148, 148, 148);\n"
        "    border: 1px solid rgb(10,10,10);\n"
        "    border-radius: 5px;\n"
        "    padding: 2px;\n"
        "}\n"
        "QLineEdit:hover{\n"
        "    border: 1px solid rgb(150,150,150);\n"
        "}\n"
        "QLineEdit:focus{\n"
        "    border: 2px solid rgb(100, 100, 255);\n"
        "}")
                self.lineEdit_fipe_value.setObjectName("lineEdit_fipe_value")
                self.verticalLayout_3.addWidget(self.lineEdit_fipe_value)
                self.lineEdit_fipe_code = QtWidgets.QLineEdit(self.frame_vehicle_plain_data_inside)
                self.lineEdit_fipe_code.setStyleSheet("QLineEdit{\n"
        "    \n"
        "    background-color: rgb(148, 148, 148);\n"
        "    border: 1px solid rgb(10,10,10);\n"
        "    border-radius: 5px;\n"
        "    padding: 2px;\n"
        "}\n"
        "QLineEdit:hover{\n"
        "    border: 1px solid rgb(150,150,150);\n"
        "}\n"
        "QLineEdit:focus{\n"
        "    border: 2px solid rgb(100, 100, 255);\n"
        "}")
                self.lineEdit_fipe_code.setObjectName("lineEdit_fipe_code")
                self.verticalLayout_3.addWidget(self.lineEdit_fipe_code)
                self.verticalLayout_9.addWidget(self.frame_vehicle_plain_data_inside)
                self.frame_plaintype_inside = QtWidgets.QFrame(self.frame_vehicle_pain_data_outside)
                self.frame_plaintype_inside.setMinimumSize(QtCore.QSize(1, 221))
                self.frame_plaintype_inside.setStyleSheet("QFrame{\n"
        "    border: 2px solid rgb(36, 183, 253);\n"
        "    border-radius: 8px;\n"
        "}")
                self.frame_plaintype_inside.setFrameShape(QtWidgets.QFrame.StyledPanel)
                self.frame_plaintype_inside.setFrameShadow(QtWidgets.QFrame.Raised)
                self.frame_plaintype_inside.setObjectName("frame_plaintype_inside")
                self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.frame_plaintype_inside)
                self.verticalLayout_11.setObjectName("verticalLayout_11")
                self.label_playntype = QtWidgets.QLabel(self.frame_plaintype_inside)
                self.label_playntype.setMinimumSize(QtCore.QSize(0, 0))
                self.label_playntype.setMaximumSize(QtCore.QSize(16777215, 20))
                font = QtGui.QFont()
                font.setFamily("Segoe UI")
                font.setPointSize(10)
                font.setBold(True)
                font.setWeight(75)
                self.label_playntype.setFont(font)
                self.label_playntype.setStyleSheet("border: no")
                self.label_playntype.setAlignment(QtCore.Qt.AlignCenter)
                self.label_playntype.setObjectName("label_playntype")
                self.verticalLayout_11.addWidget(self.label_playntype)
                self.radioButton_monitoring = QtWidgets.QRadioButton(self.frame_plaintype_inside)
                font = QtGui.QFont()
                font.setFamily("Segoe UI")
                font.setBold(True)
                font.setWeight(75)
                self.radioButton_monitoring.setFont(font)
                self.radioButton_monitoring.setStyleSheet("QRadioButton{\n"
        "    background-color: rgb(92, 230, 255);\n"
        "}\n"
        "QRadioButton:hover{\n"
        "    color: rgb(0, 0, 255);\n"
        "}")
                self.radioButton_monitoring.setObjectName("radioButton_monitoring")
                self.verticalLayout_11.addWidget(self.radioButton_monitoring)
                self.radioButton_bronze01 = QtWidgets.QRadioButton(self.frame_plaintype_inside)
                font = QtGui.QFont()
                font.setFamily("Segoe UI")
                font.setBold(True)
                font.setWeight(75)
                self.radioButton_bronze01.setFont(font)
                self.radioButton_bronze01.setStyleSheet("QRadioButton{\n"
        "    background-color: rgb(92, 230, 255);\n"
        "}\n"
        "QRadioButton:hover{\n"
        "    color: rgb(0, 0, 255);\n"
        "}")
                self.radioButton_bronze01.setObjectName("radioButton_bronze01")
                self.verticalLayout_11.addWidget(self.radioButton_bronze01)
                self.radioButton_bronze02 = QtWidgets.QRadioButton(self.frame_plaintype_inside)
                font = QtGui.QFont()
                font.setFamily("Segoe UI")
                font.setBold(True)
                font.setWeight(75)
                self.radioButton_bronze02.setFont(font)
                self.radioButton_bronze02.setStyleSheet("QRadioButton{\n"
        "    background-color: rgb(92, 230, 255);\n"
        "}\n"
        "QRadioButton:hover{\n"
        "    color: rgb(0, 0, 255);\n"
        "}")
                self.radioButton_bronze02.setObjectName("radioButton_bronze02")
                self.verticalLayout_11.addWidget(self.radioButton_bronze02)
                self.radioButton_silver01 = QtWidgets.QRadioButton(self.frame_plaintype_inside)
                font = QtGui.QFont()
                font.setFamily("Segoe UI")
                font.setBold(True)
                font.setWeight(75)
                self.radioButton_silver01.setFont(font)
                self.radioButton_silver01.setStyleSheet("QRadioButton{\n"
        "    background-color: rgb(92, 230, 255);\n"
        "}\n"
        "QRadioButton:hover{\n"
        "    color: rgb(0, 0, 255);\n"
        "}")
                self.radioButton_silver01.setObjectName("radioButton_silver01")
                self.verticalLayout_11.addWidget(self.radioButton_silver01)
                self.radioButton_silver02 = QtWidgets.QRadioButton(self.frame_plaintype_inside)
                font = QtGui.QFont()
                font.setFamily("Segoe UI")
                font.setBold(True)
                font.setWeight(75)
                self.radioButton_silver02.setFont(font)
                self.radioButton_silver02.setStyleSheet("QRadioButton{\n"
        "    background-color: rgb(92, 230, 255);\n"
        "}\n"
        "QRadioButton:hover{\n"
        "    color: rgb(0, 0, 255);\n"
        "}")
                self.radioButton_silver02.setObjectName("radioButton_silver02")
                self.verticalLayout_11.addWidget(self.radioButton_silver02)
                self.radioButton_gold = QtWidgets.QRadioButton(self.frame_plaintype_inside)
                font = QtGui.QFont()
                font.setFamily("Segoe UI")
                font.setBold(True)
                font.setWeight(75)
                self.radioButton_gold.setFont(font)
                self.radioButton_gold.setStyleSheet("QRadioButton{\n"
        "    background-color: rgb(92, 230, 255);\n"
        "}\n"
        "QRadioButton:hover{\n"
        "    color: rgb(0, 0, 255);\n"
        "}")
                self.radioButton_gold.setObjectName("radioButton_gold")
                self.verticalLayout_11.addWidget(self.radioButton_gold)
                self.verticalLayout_9.addWidget(self.frame_plaintype_inside)
                self.horizontalLayout_3.addWidget(self.frame_vehicle_pain_data_outside)
                self.frame_financial_buttons = QtWidgets.QFrame(self.frame_fill_fiedls)
                self.frame_financial_buttons.setMinimumSize(QtCore.QSize(0, 0))
                self.frame_financial_buttons.setMaximumSize(QtCore.QSize(300, 16777215))
                self.frame_financial_buttons.setStyleSheet("")
                self.frame_financial_buttons.setFrameShape(QtWidgets.QFrame.StyledPanel)
                self.frame_financial_buttons.setFrameShadow(QtWidgets.QFrame.Raised)
                self.frame_financial_buttons.setObjectName("frame_financial_buttons")
                self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.frame_financial_buttons)
                self.verticalLayout_10.setObjectName("verticalLayout_10")
                self.frame_financial = QtWidgets.QFrame(self.frame_financial_buttons)
                self.frame_financial.setMinimumSize(QtCore.QSize(161, 200))
                self.frame_financial.setMaximumSize(QtCore.QSize(300, 16777215))
                self.frame_financial.setStyleSheet("QFrame{\n"
        "    background-color: rgb(139, 253, 137);\n"
        "    border-radius: 8px;\n"
        "}")
                self.frame_financial.setFrameShape(QtWidgets.QFrame.StyledPanel)
                self.frame_financial.setFrameShadow(QtWidgets.QFrame.Raised)
                self.frame_financial.setObjectName("frame_financial")
                self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.frame_financial)
                self.verticalLayout_6.setObjectName("verticalLayout_6")
                self.label_clientdata_5 = QtWidgets.QLabel(self.frame_financial)
                self.label_clientdata_5.setMinimumSize(QtCore.QSize(0, 0))
                self.label_clientdata_5.setMaximumSize(QtCore.QSize(16777215, 20))
                font = QtGui.QFont()
                font.setFamily("Segoe UI")
                font.setPointSize(10)
                font.setBold(True)
                font.setWeight(75)
                self.label_clientdata_5.setFont(font)
                self.label_clientdata_5.setStyleSheet("QLabel{\n"
        "    border:no;\n"
        "}")
                self.label_clientdata_5.setAlignment(QtCore.Qt.AlignCenter)
                self.label_clientdata_5.setObjectName("label_clientdata_5")
                self.verticalLayout_6.addWidget(self.label_clientdata_5)
                self.lineEdit_monthly_payment = QtWidgets.QLineEdit(self.frame_financial)
                self.lineEdit_monthly_payment.setStyleSheet("QLineEdit{\n"
        "    \n"
        "    background-color: rgb(142, 216, 141);\n"
        "    border: 2px solid rgb(0, 102, 52);\n"
        "    border-radius: 5px;\n"
        "    padding: 2px;\n"
        "}\n"
        "QLineEdit:hover{\n"
        "    border: 2px solid rgb(100, 202, 152);\n"
        "}\n"
        "QLineEdit:focus{\n"
        "    border: 2px solid rgb(0, 0, 255);\n"
        "}")
                self.lineEdit_monthly_payment.setObjectName("lineEdit_monthly_payment")
                self.verticalLayout_6.addWidget(self.lineEdit_monthly_payment)
                self.lineEdit_membership_fee = QtWidgets.QLineEdit(self.frame_financial)
                self.lineEdit_membership_fee.setStyleSheet("QLineEdit{\n"
        "    \n"
        "    background-color: rgb(142, 216, 141);\n"
        "    border: 2px solid rgb(0, 102, 52);\n"
        "    border-radius: 5px;\n"
        "    padding: 2px;\n"
        "}\n"
        "QLineEdit:hover{\n"
        "    border: 2px solid rgb(100, 202, 152);\n"
        "}\n"
        "QLineEdit:focus{\n"
        "    border: 2px solid rgb(0, 0, 255);\n"
        "}")
                self.lineEdit_membership_fee.setObjectName("lineEdit_membership_fee")
                self.verticalLayout_6.addWidget(self.lineEdit_membership_fee)
                self.lineEdit_total_payment = QtWidgets.QLineEdit(self.frame_financial)
                self.lineEdit_total_payment.setStyleSheet("QLineEdit{\n"
        "    \n"
        "    background-color: rgb(142, 216, 141);\n"
        "    border: 2px solid rgb(0, 102, 52);\n"
        "    border-radius: 5px;\n"
        "    padding: 2px;\n"
        "}\n"
        "QLineEdit:hover{\n"
        "    border: 2px solid rgb(100, 202, 152);\n"
        "}\n"
        "QLineEdit:focus{\n"
        "    border: 2px solid rgb(0, 0, 255);\n"
        "}")
                self.lineEdit_total_payment.setObjectName("lineEdit_total_payment")
                self.verticalLayout_6.addWidget(self.lineEdit_total_payment)
                self.frame_playndate = QtWidgets.QFrame(self.frame_financial)
                self.frame_playndate.setMaximumSize(QtCore.QSize(16777215, 142))
                font = QtGui.QFont()
                font.setFamily("Segoe UI")
                self.frame_playndate.setFont(font)
                self.frame_playndate.setFrameShape(QtWidgets.QFrame.StyledPanel)
                self.frame_playndate.setFrameShadow(QtWidgets.QFrame.Raised)
                self.frame_playndate.setObjectName("frame_playndate")
                self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.frame_playndate)
                self.verticalLayout_12.setObjectName("verticalLayout_12")
                self.label_start = QtWidgets.QLabel(self.frame_playndate)
                self.label_start.setMaximumSize(QtCore.QSize(16777215, 30))
                font = QtGui.QFont()
                font.setBold(True)
                font.setWeight(75)
                self.label_start.setFont(font)
                self.label_start.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
                self.label_start.setObjectName("label_start")
                self.verticalLayout_12.addWidget(self.label_start)
                self.dateEdit_start = QtWidgets.QDateEdit(self.frame_playndate)
                font = QtGui.QFont()
                font.setFamily("Segoe UI")
                self.dateEdit_start.setFont(font)
                self.dateEdit_start.setStyleSheet("")
                self.dateEdit_start.setObjectName("dateEdit_start")
                self.verticalLayout_12.addWidget(self.dateEdit_start)
                self.label_finish = QtWidgets.QLabel(self.frame_playndate)
                self.label_finish.setMaximumSize(QtCore.QSize(16777215, 30))
                font = QtGui.QFont()
                font.setFamily("Segoe UI")
                font.setBold(True)
                font.setWeight(75)
                self.label_finish.setFont(font)
                self.label_finish.setObjectName("label_finish")
                self.verticalLayout_12.addWidget(self.label_finish)
                self.dateEdit_finish = QtWidgets.QDateEdit(self.frame_playndate)
                font = QtGui.QFont()
                font.setFamily("Segoe UI")
                self.dateEdit_finish.setFont(font)
                self.dateEdit_finish.setObjectName("dateEdit_finish")
                self.verticalLayout_12.addWidget(self.dateEdit_finish)
                self.verticalLayout_6.addWidget(self.frame_playndate)
                self.verticalLayout_10.addWidget(self.frame_financial)
                self.frame_buttons_observations = QtWidgets.QFrame(self.frame_financial_buttons)
                self.frame_buttons_observations.setStyleSheet("QFrame{\n"
        "    border: no\n"
        "}")
                self.frame_buttons_observations.setFrameShape(QtWidgets.QFrame.StyledPanel)
                self.frame_buttons_observations.setFrameShadow(QtWidgets.QFrame.Raised)
                self.frame_buttons_observations.setObjectName("frame_buttons_observations")
                self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.frame_buttons_observations)
                self.verticalLayout_7.setObjectName("verticalLayout_7")
                self.pushButton_adhesion = QtWidgets.QPushButton(self.frame_buttons_observations)
                self.pushButton_adhesion.setMinimumSize(QtCore.QSize(20, 22))
                self.pushButton_adhesion.setMaximumSize(QtCore.QSize(16777215, 16777215))
                font = QtGui.QFont()
                font.setFamily("Segoe UI")
                self.pushButton_adhesion.setFont(font)
                self.pushButton_adhesion.setStyleSheet("QPushButton{\n"
        "    border: 1px solid rgb(10, 10, 10);\n"
        "    border-radius: 5px;\n"
        "    background-color: rgb(136, 230, 253);\n"
        "}\n"
        "QPushButton:hover{\n"
        "    border: 1px solid rgb(150,150,150);\n"
        "}\n"
        "QPushButton:pressed{\n"
        "    border: 2px solid rgb(50, 50, 255);\n"
        "}")
                self.pushButton_adhesion.setObjectName("pushButton_adhesion")
                self.verticalLayout_7.addWidget(self.pushButton_adhesion)
                self.pushButton_forwarding = QtWidgets.QPushButton(self.frame_buttons_observations)
                self.pushButton_forwarding.setMinimumSize(QtCore.QSize(20, 22))
                self.pushButton_forwarding.setMaximumSize(QtCore.QSize(16777215, 16777215))
                font = QtGui.QFont()
                font.setFamily("Segoe UI")
                self.pushButton_forwarding.setFont(font)
                self.pushButton_forwarding.setStyleSheet("QPushButton{\n"
        "    border: 1px solid rgb(10, 10, 10);\n"
        "    border-radius: 5px;\n"
        "    background-color: rgb(136, 230, 253);\n"
        "}\n"
        "QPushButton:hover{\n"
        "    border: 1px solid rgb(150,150,150);\n"
        "}\n"
        "QPushButton:pressed{\n"
        "    border: 2px solid rgb(50, 50, 255);\n"
        "}")
                self.pushButton_forwarding.setObjectName("pushButton_forwarding")
                self.verticalLayout_7.addWidget(self.pushButton_forwarding)
                self.pushButton_vehicle_delivery = QtWidgets.QPushButton(self.frame_buttons_observations)
                self.pushButton_vehicle_delivery.setMinimumSize(QtCore.QSize(20, 22))
                self.pushButton_vehicle_delivery.setMaximumSize(QtCore.QSize(16777215, 16777215))
                font = QtGui.QFont()
                font.setFamily("Segoe UI")
                self.pushButton_vehicle_delivery.setFont(font)
                self.pushButton_vehicle_delivery.setStyleSheet("QPushButton{\n"
        "    border: 1px solid rgb(10, 10, 10);\n"
        "    border-radius: 5px;\n"
        "    background-color: rgb(136, 230, 253);\n"
        "}\n"
        "QPushButton:hover{\n"
        "    border: 1px solid rgb(150,150,150);\n"
        "}\n"
        "QPushButton:pressed{\n"
        "    border: 2px solid rgb(50, 50, 255);\n"
        "}")
                self.pushButton_vehicle_delivery.setObjectName("pushButton_vehicle_delivery")
                self.verticalLayout_7.addWidget(self.pushButton_vehicle_delivery)
                self.pushButton_receipt = QtWidgets.QPushButton(self.frame_buttons_observations)
                self.pushButton_receipt.setMinimumSize(QtCore.QSize(20, 22))
                self.pushButton_receipt.setMaximumSize(QtCore.QSize(16777215, 16777215))
                font = QtGui.QFont()
                font.setFamily("Segoe UI")
                self.pushButton_receipt.setFont(font)
                self.pushButton_receipt.setStyleSheet("QPushButton{\n"
        "    border: 1px solid rgb(10, 10, 10);\n"
        "    border-radius: 5px;\n"
        "    background-color: rgb(136, 230, 253);\n"
        "}\n"
        "QPushButton:hover{\n"
        "    border: 1px solid rgb(150,150,150);\n"
        "}\n"
        "QPushButton:pressed{\n"
        "    border: 2px solid rgb(50, 50, 255);\n"
        "}")
                self.pushButton_receipt.setObjectName("pushButton_receipt")
                self.verticalLayout_7.addWidget(self.pushButton_receipt)
                self.pushButton_cancel = QtWidgets.QPushButton(self.frame_buttons_observations)
                self.pushButton_cancel.setMinimumSize(QtCore.QSize(20, 22))
                self.pushButton_cancel.setMaximumSize(QtCore.QSize(16777215, 16777215))
                font = QtGui.QFont()
                font.setFamily("Segoe UI")
                font.setBold(True)
                font.setWeight(75)
                self.pushButton_cancel.setFont(font)
                self.pushButton_cancel.setStyleSheet("QPushButton{\n"
        "    border: 1px solid rgb(10, 10, 10);\n"
        "    border-radius: 5px;\n"
        "    background-color: rgb(136, 230, 253);\n"
        "    color: rgb(255, 0, 0);\n"
        "}\n"
        "QPushButton:hover{\n"
        "    border: 1px solid rgb(150,150,150);\n"
        "}\n"
        "QPushButton:pressed{\n"
        "    border: 2px solid rgb(255, 0, 0);\n"
        "}")
                self.pushButton_cancel.setObjectName("pushButton_cancel")
                self.verticalLayout_7.addWidget(self.pushButton_cancel)
                self.textEdit_observations = QtWidgets.QTextEdit(self.frame_buttons_observations)
                self.textEdit_observations.setMaximumSize(QtCore.QSize(16777215, 16777215))
                self.textEdit_observations.setStyleSheet("QTextEdit{\n"
        "    \n"
        "    background-color: rgb(255, 255, 255);\n"
        "    border: 1px solid rgb(10,10,10);\n"
        "    border-radius: 5px;\n"
        "    padding: 2px;\n"
        "}\n"
        "QTextEdit:hover{\n"
        "    border: 2px solid rgb(200,200,200);\n"
        "}\n"
        "QTextEdit:focus{\n"
        "    border: 2px solid rgb(0, 0, 255);\n"
        "}")
                self.textEdit_observations.setObjectName("textEdit_observations")
                self.verticalLayout_7.addWidget(self.textEdit_observations)
                self.label_credits = QtWidgets.QLabel(self.frame_buttons_observations)
                self.label_credits.setMaximumSize(QtCore.QSize(16777215, 16777215))
                font = QtGui.QFont()
                font.setFamily("Segoe UI")
                font.setBold(True)
                font.setItalic(True)
                font.setWeight(75)
                self.label_credits.setFont(font)
                self.label_credits.setLayoutDirection(QtCore.Qt.RightToLeft)
                self.label_credits.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
                self.label_credits.setObjectName("label_credits")
                self.verticalLayout_7.addWidget(self.label_credits)
                self.verticalLayout_10.addWidget(self.frame_buttons_observations)
                self.horizontalLayout_3.addWidget(self.frame_financial_buttons)
                self.horizontalLayout_2.addWidget(self.frame_fill_fiedls)
                self.scrollArea.setWidget(self.scrollAreaWidgetContents)
                self.horizontalLayout.addWidget(self.scrollArea)
                MainWindow.setCentralWidget(self.centralwidget)
                self.actionGerar_termo_de_ades_o = QtWidgets.QAction(MainWindow)
                self.actionGerar_termo_de_ades_o.setObjectName("actionGerar_termo_de_ades_o")
                self.actionNovo = QtWidgets.QAction(MainWindow)
                self.actionNovo.setObjectName("actionNovo")
                self.actionSalvar = QtWidgets.QAction(MainWindow)
                self.actionSalvar.setObjectName("actionSalvar")
                self.actionGerar_Termo_em_PDF = QtWidgets.QAction(MainWindow)
                self.actionGerar_Termo_em_PDF.setObjectName("actionGerar_Termo_em_PDF")
                self.actionImprimir_Termo = QtWidgets.QAction(MainWindow)
                self.actionImprimir_Termo.setObjectName("actionImprimir_Termo")
                self.actionImprimir_Termo_2 = QtWidgets.QAction(MainWindow)
                self.actionImprimir_Termo_2.setObjectName("actionImprimir_Termo_2")


                #
                #FUNCTIONS
                #

                self.pushButton_adhesion.pressed.connect(self.GenerateTermOfAdhesion)
                #self.pushButton_cancel.pressed.connect()


                self.retranslateUi(MainWindow)
                QtCore.QMetaObject.connectSlotsByName(MainWindow)

        def retranslateUi(self, MainWindow):
                _translate = QtCore.QCoreApplication.translate
                MainWindow.setWindowTitle(_translate("MainWindow", "Sistema de Gerenciamento de Segurados"))
                self.textBrowser_logo_name.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
        "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
        "p, li { white-space: pre-wrap; }\n"
        "</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
        "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">PMS - Policyholder Management System</span></p>\n"
        "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">Sistema de Gerenciamento de Segurados</span></p></body></html>"))
                self.label_coverage.setText(_translate("MainWindow", "COBERTURAS"))
                self.checkBox_monitoring.setText(_translate("MainWindow", "Monitoramento e Rastreamento"))
                self.checkBox_robbery.setText(_translate("MainWindow", "Roubo"))
                self.checkBox_theft.setText(_translate("MainWindow", "Furto"))
                self.checkBox_pt.setText(_translate("MainWindow", "Perda Total"))
                self.checkBox_collision.setText(_translate("MainWindow", "Colisão do Associado"))
                self.checkBox_winch3.setText(_translate("MainWindow", "3 Reboques Gratuitos a.a."))
                self.checkBox_winch6.setText(_translate("MainWindow", "6 Reboques Gratuitos a.a."))
                self.checkBox_unlimited_winch.setText(_translate("MainWindow", "Reboque Ilimitado"))
                self.checkBox_winch500.setText(_translate("MainWindow", "Quinhentos Quilômetros de Reboque"))
                self.checkBox_glasses.setText(_translate("MainWindow", "Vidros em Geral"))
                self.checkBox_others.setText(_translate("MainWindow", "Terceiros"))
                self.label_clientdata.setText(_translate("MainWindow", "DADOS DO CLIENTE"))
                self.lineEdit_name.setPlaceholderText(_translate("MainWindow", "NOME"))
                self.lineEdit_cpf.setPlaceholderText(_translate("MainWindow", "CPF"))
                self.lineEdit_rg.setPlaceholderText(_translate("MainWindow", "RG"))
                self.lineEdit_phone1.setPlaceholderText(_translate("MainWindow", "TELEFONE 1"))
                self.lineEdit_phone2.setPlaceholderText(_translate("MainWindow", "TELEFONE 2"))
                self.label_adress.setText(_translate("MainWindow", "ENDEREÇO"))
                self.lineEdit_street.setPlaceholderText(_translate("MainWindow", "RUA/AV"))
                self.lineEdit_number.setPlaceholderText(_translate("MainWindow", "NUMERO"))
                self.lineEdit_comp.setPlaceholderText(_translate("MainWindow", "COMPLEMENTO"))
                self.lineEdit_neghbordhood.setPlaceholderText(_translate("MainWindow", "BAIRRO"))
                self.lineEdit_city.setPlaceholderText(_translate("MainWindow", "CIDADE"))
                self.lineEdit_uf.setPlaceholderText(_translate("MainWindow", "UF"))
                self.lineEdit_cep.setPlaceholderText(_translate("MainWindow", "CEP"))
                self.label_vehicle.setText(_translate("MainWindow", "DADOS DO VEÍCULO"))
                self.lineEdit_assembler.setPlaceholderText(_translate("MainWindow", "MONTADORA"))
                self.lineEdit_model.setPlaceholderText(_translate("MainWindow", "MODELO"))
                self.lineEdit_plate.setPlaceholderText(_translate("MainWindow", "PLACA"))
                self.lineEdit_color.setPlaceholderText(_translate("MainWindow", "COR"))
                self.lineEdit_year.setPlaceholderText(_translate("MainWindow", "ANO"))
                self.lineEdit_chassis.setPlaceholderText(_translate("MainWindow", "CHASSI"))
                self.lineEdit_renavam.setPlaceholderText(_translate("MainWindow", "RENAVAM"))
                self.lineEdit_fipe_value.setPlaceholderText(_translate("MainWindow", "FALOR - FIPE"))
                self.lineEdit_fipe_code.setPlaceholderText(_translate("MainWindow", "COD - FIPE"))
                self.label_playntype.setText(_translate("MainWindow", "TIPO DE PLANO"))
                self.radioButton_monitoring.setText(_translate("MainWindow", "Rastreamento e Monitoramento"))
                self.radioButton_bronze01.setText(_translate("MainWindow", "Bronze - 01"))
                self.radioButton_bronze02.setText(_translate("MainWindow", "Bronze - 02"))
                self.radioButton_silver01.setText(_translate("MainWindow", "Prata - 01"))
                self.radioButton_silver02.setText(_translate("MainWindow", "Prata - 02"))
                self.radioButton_gold.setText(_translate("MainWindow", "Ouro"))
                self.label_clientdata_5.setText(_translate("MainWindow", "FINANCEIRO"))
                self.lineEdit_monthly_payment.setPlaceholderText(_translate("MainWindow", "MENSALIDADE"))
                self.lineEdit_membership_fee.setPlaceholderText(_translate("MainWindow", "TAXA DE ADESÃO/CANCELAMENTO"))
                self.lineEdit_total_payment.setPlaceholderText(_translate("MainWindow", "PARCELA ÚNICA (PAGTO TOTAL DE PLANO)"))
                self.label_start.setText(_translate("MainWindow", "Plano válido de:"))
                self.label_finish.setText(_translate("MainWindow", "Até"))
                self.pushButton_adhesion.setText(_translate("MainWindow", "Gerar Termo de Adesão"))
                self.pushButton_forwarding.setText(_translate("MainWindow", "Gerar Termo de Encaminhamento"))
                self.pushButton_vehicle_delivery.setText(_translate("MainWindow", "Gerar Termo de Entrega de Veículo"))
                self.pushButton_receipt.setText(_translate("MainWindow", "Gerar Recibo"))
                self.pushButton_cancel.setText(_translate("MainWindow", "Gerar Termo de Cancelamento"))
                self.textEdit_observations.setPlaceholderText(_translate("MainWindow", "OBSERVAÇÕES"))
                self.label_credits.setText(_translate("MainWindow", "Created by Sérgio Lima - V4"))
                self.actionGerar_termo_de_ades_o.setText(_translate("MainWindow", "Gerar termo de adesão"))
                self.actionNovo.setText(_translate("MainWindow", "Novo..."))
                self.actionSalvar.setText(_translate("MainWindow", "Salvar"))
                self.actionGerar_Termo_em_PDF.setText(_translate("MainWindow", "Gerar Termo em PDF"))
                self.actionImprimir_Termo.setText(_translate("MainWindow", "Imprimir Termo"))
                self.actionImprimir_Termo_2.setText(_translate("MainWindow", "Imprimir Termo"))
        import file_rcV4


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
