# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'PMSPolicyholder.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from reportlab.pdfgen import canvas
from reportlab.lib.pagesizes import A4
from datetime import date


class Ui_MainWindow(object):

        def GenerateTermInPDF(self):
                self.cnv = canvas.Canvas('GeraPDF.pdf')
                self.cnv.drawImage('background-maximaprotecao.png',x=50,y=30,width=500,height=800)
                # INSERT HEADER
                self.cnv.drawImage('header.png',x=70,y=565,width=470,height=80)

                #INSERT PLAIN TYPE
                self.plain_selected = str()
                if self.radioButton_monitoring.isChecked():
                        self.plain_selected = self.label_monitoring.text()
                if self.radioButton_bronze01.isChecked():
                        self.plain_selected = self.label_bronze01.text()
                if self.radioButton_bronze02.isChecked():
                        self.plain_selected = self.label_bronze02.text()
                if self.radioButton_silver01.isChecked():
                        self.plain_selected = self.label_silver01.text()
                if self.radioButton_silver02.isChecked():
                        self.plain_selected = self.label_silver02.text()
                if self.radioButton_gold.isChecked():
                        self.plain_selected = self.label_gold.text()
                self.cnv.drawString(x=170,y=573,text= self.plain_selected.upper(), mode=1)
                #INSERT TITLE
                self.cnv.drawString(x=250, y=700,text="TERMO DE ADESÃO",mode=1)

                #INSERT RETANGULE POLICYHOLDER DATA
                self.cnv.rect(55,470,500,45)
                #HORIZONTAL LINE
                self.cnv.line(55,492,554,492)
                #VERTICAL LINE
                self.cnv.line(100,515,100,470)

                # POLICYHOLDER DATA
                self.cnv.drawString(x=55,y=520,text='DADOS DO CLIENTE',mode=1)
                self.cnv.drawString(x=60,y=500, text= 'NOME')
                self.cnv.drawString(x=60,y=480, text= ' CPF')
                self.cnv.drawString(x=110,y=500, text= self.lineEdit_name.text())
                self.cnv.drawString(x=110,y=480, text= self.lineEdit_cpf.text())

                #INSERT RECTANGULE VEHICLE DATA
                self.cnv.rect(55,345,500,77)
                        #HORIZONTAL LINE
                self.cnv.line(55,405,554,405)
                self.cnv.line(55,385,554,385)
                self.cnv.line(55,365,554,365)
                        #VERTICAL LINE
                self.cnv.line(140,422,140,345)

                        #VEHICLE DATA TITLES
                self.cnv.drawString(x=55,y=430,text='VEÍCULO',mode=1)
                self.cnv.drawString(x=60,y=410, text= 'MONTADORA')
                self.cnv.drawString(x=60,y=390, text= 'MODELO')
                self.cnv.drawString(x=60,y=370, text= 'PLACA')
                self.cnv.drawString(x=60,y=350, text= ' COR')
                        #VEHICLE DATA TEXTS
                self.cnv.drawString(x=150,y=410, text= self.lineEdit_assembler.text())
                self.cnv.drawString(x=150,y=390, text= self.lineEdit_model.text())
                self.cnv.drawString(x=150,y=370, text= self.lineEdit_plate.text())
                self.cnv.drawString(x=150,y=350, text= self.lineEdit_color.text())

                #INSERT RECTANGULE COVERAGE DATA
                self.cnv.rect(55,150,500,145)
                #COVERAGE DATA
                self.cnv.drawString(x=55,y=300,text='COBERTURA / PLANO',mode=1)
                self.coverages = []
                
                        # COVERAGE SELECTION
                if self.checkBox_monitoring.isChecked():
                        self.coverages.append(self.checkBox_monitoring.text())
                if self.checkBox_robbery.isChecked():
                        self.coverages.append(self.checkBox_robbery.text())
                if self.checkBox_theft.isChecked():
                        self.coverages.append(self.checkBox_theft.text())
                if self.checkBox_collision.isChecked():
                        self.coverages.append(self.checkBox_collision.text())
                if self.checkBox_pt.isChecked():
                        self.coverages.append(self.checkBox_pt.text())
                if self.checkBox_3R.isChecked():
                        self.coverages.append(self.checkBox_3R.text())
                if self.checkBox_6R.isChecked():
                        self.coverages.append(self.checkBox_6R.text())
                if self.checkBox_RUnlimited.isChecked():
                        self.coverages.append(self.checkBox_RUnlimited.text())
                if self.checkBox_R500.isChecked():
                        self.coverages.append(self.checkBox_R500.text())
                if self.checkBox_glasses.isChecked():
                        self.coverages.append(self.checkBox_glasses.text())
                if self.checkBox_others.isChecked():
                        self.coverages.append(self.checkBox_others.text())

                space_x = 60
                space_y = 280
                for coverage in self.coverages:
                        self.cnv.drawString(space_x,space_y,coverage)
                        space_y -= 12

                #INSERT SIGNATURE
                self.cnv.drawImage('signature_mp.png',x=115,y=65,width=60,height=70)
                self.cnv.drawString(55,90,'MAXIMA PROTEÇÃO VEÍCULAR',mode=1)

                #INSERT DATE
                day = date.today().day
                month = date.today().month
                year = date.today().year

                month_current = str()
                if month == 1:
                        month_current = 'JANEIRO'
                elif month == 2:
                        month_current = 'FEVEREIRO'
                elif month == 3:
                        month_current = 'MARCO'
                elif month == 4:
                        month_current = 'ABRIL'
                elif month == 5:
                        month_current = 'MAIO'
                elif month == 6:
                        month_current = 'JUNHO'
                elif month == 7:
                        month_current = 'JULHO'
                elif month == 8:
                        month_current = 'AGOSTO'
                elif month == 9:
                        month_current = 'SETEMBRO'
                elif month == 10:
                        month_current = 'OUTUBRO'
                elif month == 11:
                        month_current = 'NOVEMBRO'
                elif month == 12:
                        month_current = 'DEZEMBRO'
                self.cnv.drawString(240,90,f' - {day} DE {month_current} DE {year}',mode=1)


                #CREATE PDF
                self.cnv.save()

        def setupUi(self, MainWindow):
                MainWindow.setObjectName("MainWindow")
                MainWindow.resize(1366, 720)
                icon = QtGui.QIcon()
                icon.addPixmap(QtGui.QPixmap("Images/icon.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
                MainWindow.setWindowIcon(icon)
                self.centralwidget = QtWidgets.QWidget(MainWindow)
                self.centralwidget.setObjectName("centralwidget")
                self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
                self.verticalLayout.setContentsMargins(0, 0, 0, 0)
                self.verticalLayout.setSpacing(0)
                self.verticalLayout.setObjectName("verticalLayout")
                self.frame_background = QtWidgets.QFrame(self.centralwidget)
                self.frame_background.setStyleSheet("background-color: rgb(255, 255, 255);")
                self.frame_background.setFrameShape(QtWidgets.QFrame.StyledPanel)
                self.frame_background.setFrameShadow(QtWidgets.QFrame.Raised)
                self.frame_background.setObjectName("frame_background")
                self.frame_logo_outside = QtWidgets.QFrame(self.frame_background)
                self.frame_logo_outside.setGeometry(QtCore.QRect(1, 1, 469, 703))
                self.frame_logo_outside.setStyleSheet("QFrame{\n"
        "    background-color: rgb(255, 255, 255);\n"
        "}")
                self.frame_logo_outside.setFrameShape(QtWidgets.QFrame.StyledPanel)
                self.frame_logo_outside.setFrameShadow(QtWidgets.QFrame.Raised)
                self.frame_logo_outside.setObjectName("frame_logo_outside")
                self.frame_logo_inside = QtWidgets.QFrame(self.frame_logo_outside)
                self.frame_logo_inside.setGeometry(QtCore.QRect(62, 180, 300, 301))
                self.frame_logo_inside.setMinimumSize(QtCore.QSize(0, 0))
                self.frame_logo_inside.setMaximumSize(QtCore.QSize(300, 1000))
                self.frame_logo_inside.setStyleSheet("background-image: url(:/Logo/Images/logomp313x300.png);\n"
        "background-repeat: no-repeat;\n"
        "background-position: center;\n"
        "")
                self.frame_logo_inside.setFrameShape(QtWidgets.QFrame.StyledPanel)
                self.frame_logo_inside.setFrameShadow(QtWidgets.QFrame.Raised)
                self.frame_logo_inside.setObjectName("frame_logo_inside")
                self.label_2 = QtWidgets.QLabel(self.frame_logo_outside)
                self.label_2.setGeometry(QtCore.QRect(20, 10, 231, 16))
                font = QtGui.QFont()
                font.setFamily("Segoe UI")
                font.setPointSize(9)
                font.setBold(False)
                font.setItalic(False)
                font.setWeight(50)
                self.label_2.setFont(font)
                self.label_2.setObjectName("label_2")
                self.label_3 = QtWidgets.QLabel(self.frame_logo_outside)
                self.label_3.setGeometry(QtCore.QRect(20, 30, 241, 21))
                font = QtGui.QFont()
                font.setFamily("Segoe UI")
                font.setPointSize(12)
                font.setBold(True)
                font.setItalic(True)
                font.setWeight(75)
                self.label_3.setFont(font)
                self.label_3.setObjectName("label_3")
                self.frame_buttons_menu = QtWidgets.QFrame(self.frame_background)
                self.frame_buttons_menu.setGeometry(QtCore.QRect(1070, 1, 300, 703))
                self.frame_buttons_menu.setMinimumSize(QtCore.QSize(0, 0))
                self.frame_buttons_menu.setMaximumSize(QtCore.QSize(300, 1000))
                self.frame_buttons_menu.setStyleSheet("border: no-border;\n"
        "background-image: url(:/backgrounds/Images/background-blue-1715x980.jpg);")
                self.frame_buttons_menu.setFrameShape(QtWidgets.QFrame.StyledPanel)
                self.frame_buttons_menu.setFrameShadow(QtWidgets.QFrame.Raised)
                self.frame_buttons_menu.setObjectName("frame_buttons_menu")
                self.pushButton_generateterm = QtWidgets.QPushButton(self.frame_buttons_menu)
                self.pushButton_generateterm.setGeometry(QtCore.QRect(20, 20, 261, 31))
                font = QtGui.QFont()
                font.setFamily("Segoe UI")
                font.setBold(True)
                font.setWeight(75)
                self.pushButton_generateterm.setFont(font)
                self.pushButton_generateterm.setStyleSheet("QPushButton{\n"
        "    border: 1px solid rgb(50, 50, 255);\n"
        "    border-radius: 5px;\n"
        "}\n"
        "QPushButton:hover{\n"
        "    border: 1px solid rgb(10, 10, 10);\n"
        "}\n"
        "QPushButton:pressed{\n"
        "    border: 2px solid rgb(0, 0, 255);\n"
        "}")
                self.pushButton_generateterm.setObjectName("pushButton_generateterm")
                self.pushButton_printterm = QtWidgets.QPushButton(self.frame_buttons_menu)
                self.pushButton_printterm.setGeometry(QtCore.QRect(20, 60, 261, 31))
                font = QtGui.QFont()
                font.setFamily("Segoe UI")
                font.setBold(True)
                font.setWeight(75)
                self.pushButton_printterm.setFont(font)
                self.pushButton_printterm.setStyleSheet("QPushButton{\n"
        "    border: 1px solid rgb(50, 50, 255);\n"
        "    border-radius: 5px;\n"
        "}\n"
        "QPushButton:hover{\n"
        "    border: 1px solid rgb(10, 10, 10);\n"
        "}\n"
        "QPushButton:pressed{\n"
        "    border: 2px solid rgb(0, 0, 255);\n"
        "}")
                self.pushButton_printterm.setObjectName("pushButton_printterm")
                self.frame_datauser_outside = QtWidgets.QFrame(self.frame_background)
                self.frame_datauser_outside.setGeometry(QtCore.QRect(770, 1, 300, 703))
                self.frame_datauser_outside.setMinimumSize(QtCore.QSize(0, 0))
                self.frame_datauser_outside.setMaximumSize(QtCore.QSize(300, 1000))
                self.frame_datauser_outside.setStyleSheet("border: no-border;\n"
        "background-image: url(:/backgrounds/Images/background-blue-1715x980.jpg);")
                self.frame_datauser_outside.setFrameShape(QtWidgets.QFrame.StyledPanel)
                self.frame_datauser_outside.setFrameShadow(QtWidgets.QFrame.Raised)
                self.frame_datauser_outside.setObjectName("frame_datauser_outside")
                self.label_clientdata = QtWidgets.QLabel(self.frame_datauser_outside)
                self.label_clientdata.setGeometry(QtCore.QRect(10, 10, 281, 51))
                font = QtGui.QFont()
                font.setFamily("Segoe UI")
                font.setBold(True)
                font.setWeight(75)
                self.label_clientdata.setFont(font)
                self.label_clientdata.setLayoutDirection(QtCore.Qt.LeftToRight)
                self.label_clientdata.setStyleSheet("QLabel{\n"
        "    border: 2px solid rgb(50,50,50);\n"
        "    border-radius: 5px;\n"
        "    \n"
        "    background-image: url(:/backgrounds/Images/background-blue-1715x980.jpg);\n"
        "}")
                self.label_clientdata.setAlignment(QtCore.Qt.AlignCenter)
                self.label_clientdata.setObjectName("label_clientdata")
                self.frame_datauser_inside = QtWidgets.QFrame(self.frame_datauser_outside)
                self.frame_datauser_inside.setGeometry(QtCore.QRect(10, 70, 281, 141))
                self.frame_datauser_inside.setStyleSheet("QFrame{\n"
        "    border: 2px solid rgb(50,50,50);\n"
        "    border-radius: 5px;\n"
        "    \n"
        "    background-image: url(:/backgrounds/Images/background-blue-1715x980.jpg);\n"
        "}")
                self.frame_datauser_inside.setFrameShape(QtWidgets.QFrame.StyledPanel)
                self.frame_datauser_inside.setFrameShadow(QtWidgets.QFrame.Raised)
                self.frame_datauser_inside.setObjectName("frame_datauser_inside")
                self.lineEdit_name = QtWidgets.QLineEdit(self.frame_datauser_inside)
                self.lineEdit_name.setGeometry(QtCore.QRect(11, 11, 261, 24))
                self.lineEdit_name.setMaximumSize(QtCore.QSize(300, 16777211))
                self.lineEdit_name.setStyleSheet("QLineEdit{\n"
        "    border: 2px solid rgb(10,10,10);\n"
        "    border-radius: 5px;\n"
        "    padding: 2px;\n"
        "}\n"
        "QLineEdit:hover{\n"
        "    border: 2px solid rgb(80,80,80);\n"
        "}\n"
        "QLineEdit:focus{\n"
        "    border: 2px solid rgb(80,80,80);\n"
        "}")
                self.lineEdit_name.setText("")
                self.lineEdit_name.setObjectName("lineEdit_name")
                self.lineEdit_cpf = QtWidgets.QLineEdit(self.frame_datauser_inside)
                self.lineEdit_cpf.setGeometry(QtCore.QRect(11, 40, 261, 24))
                self.lineEdit_cpf.setMaximumSize(QtCore.QSize(300, 16777211))
                self.lineEdit_cpf.setStyleSheet("QLineEdit{\n"
        "    border: 2px solid rgb(10,10,10);\n"
        "    border-radius: 5px;\n"
        "    padding: 2px;\n"
        "}\n"
        "QLineEdit:hover{\n"
        "    border: 2px solid rgb(80,80,80);\n"
        "}\n"
        "QLineEdit:focus{\n"
        "    border: 2px solid rgb(80,80,80);\n"
        "}")
                self.lineEdit_cpf.setText("")
                self.lineEdit_cpf.setObjectName("lineEdit_cpf")
                self.lineEdit_rg = QtWidgets.QLineEdit(self.frame_datauser_inside)
                self.lineEdit_rg.setGeometry(QtCore.QRect(11, 70, 261, 24))
                self.lineEdit_rg.setMaximumSize(QtCore.QSize(300, 16777211))
                self.lineEdit_rg.setStyleSheet("QLineEdit{\n"
        "    border: 2px solid rgb(10,10,10);\n"
        "    border-radius: 5px;\n"
        "    padding: 2px;\n"
        "}\n"
        "QLineEdit:hover{\n"
        "    border: 2px solid rgb(80,80,80);\n"
        "}\n"
        "QLineEdit:focus{\n"
        "    border: 2px solid rgb(80,80,80);\n"
        "}")
                self.lineEdit_rg.setText("")
                self.lineEdit_rg.setObjectName("lineEdit_rg")
                self.lineEdit_phone = QtWidgets.QLineEdit(self.frame_datauser_inside)
                self.lineEdit_phone.setGeometry(QtCore.QRect(11, 100, 261, 24))
                self.lineEdit_phone.setMaximumSize(QtCore.QSize(300, 16777211))
                self.lineEdit_phone.setStyleSheet("QLineEdit{\n"
        "    border: 2px solid rgb(10,10,10);\n"
        "    border-radius: 5px;\n"
        "    padding: 2px;\n"
        "}\n"
        "QLineEdit:hover{\n"
        "    border: 2px solid rgb(80,80,80);\n"
        "}\n"
        "QLineEdit:focus{\n"
        "    border: 2px solid rgb(80,80,80);\n"
        "}")
                self.lineEdit_phone.setText("")
                self.lineEdit_phone.setObjectName("lineEdit_phone")
                self.frame_vehicledata_plaintype_outside = QtWidgets.QFrame(self.frame_datauser_outside)
                self.frame_vehicledata_plaintype_outside.setGeometry(QtCore.QRect(0, 220, 300, 431))
                self.frame_vehicledata_plaintype_outside.setMinimumSize(QtCore.QSize(0, 0))
                self.frame_vehicledata_plaintype_outside.setMaximumSize(QtCore.QSize(300, 1000))
                self.frame_vehicledata_plaintype_outside.setStyleSheet("border: no-border;")
                self.frame_vehicledata_plaintype_outside.setFrameShape(QtWidgets.QFrame.StyledPanel)
                self.frame_vehicledata_plaintype_outside.setFrameShadow(QtWidgets.QFrame.Raised)
                self.frame_vehicledata_plaintype_outside.setObjectName("frame_vehicledata_plaintype_outside")
                self.label_vehicle = QtWidgets.QLabel(self.frame_vehicledata_plaintype_outside)
                self.label_vehicle.setGeometry(QtCore.QRect(10, 10, 281, 51))
                font = QtGui.QFont()
                font.setFamily("Segoe UI")
                font.setBold(True)
                font.setWeight(75)
                self.label_vehicle.setFont(font)
                self.label_vehicle.setLayoutDirection(QtCore.Qt.LeftToRight)
                self.label_vehicle.setStyleSheet("QLabel{\n"
        "    border: 2px solid rgb(50,50,50);\n"
        "    border-radius: 5px;\n"
        "    \n"
        "    background-color: rgb(170, 255, 255);\n"
        "}")
                self.label_vehicle.setAlignment(QtCore.Qt.AlignCenter)
                self.label_vehicle.setObjectName("label_vehicle")
                self.frame_vehicledata_plaintype__inside = QtWidgets.QFrame(self.frame_vehicledata_plaintype_outside)
                self.frame_vehicledata_plaintype__inside.setGeometry(QtCore.QRect(10, 70, 281, 141))
                self.frame_vehicledata_plaintype__inside.setStyleSheet("QFrame{\n"
        "    border: 2px solid rgb(50,50,50);\n"
        "    border-radius: 5px;\n"
        "    \n"
        "    background-image: url(:/backgrounds/Images/background-blue-1715x980.jpg);\n"
        "}")
                self.frame_vehicledata_plaintype__inside.setFrameShape(QtWidgets.QFrame.StyledPanel)
                self.frame_vehicledata_plaintype__inside.setFrameShadow(QtWidgets.QFrame.Raised)
                self.frame_vehicledata_plaintype__inside.setObjectName("frame_vehicledata_plaintype__inside")
                self.lineEdit_assembler = QtWidgets.QLineEdit(self.frame_vehicledata_plaintype__inside)
                self.lineEdit_assembler.setGeometry(QtCore.QRect(11, 11, 261, 24))
                self.lineEdit_assembler.setMaximumSize(QtCore.QSize(300, 16777211))
                self.lineEdit_assembler.setStyleSheet("QLineEdit{\n"
        "    border: 2px solid rgb(10,10,10);\n"
        "    border-radius: 5px;\n"
        "    padding: 2px;\n"
        "}\n"
        "QLineEdit:hover{\n"
        "    border: 2px solid rgb(80,80,80);\n"
        "}\n"
        "QLineEdit:focus{\n"
        "    border: 2px solid rgb(80,80,80);\n"
        "}")
                self.lineEdit_assembler.setText("")
                self.lineEdit_assembler.setObjectName("lineEdit_assembler")
                self.lineEdit_model = QtWidgets.QLineEdit(self.frame_vehicledata_plaintype__inside)
                self.lineEdit_model.setGeometry(QtCore.QRect(10, 40, 261, 24))
                self.lineEdit_model.setMaximumSize(QtCore.QSize(300, 16777211))
                self.lineEdit_model.setStyleSheet("QLineEdit{\n"
        "    border: 2px solid rgb(10,10,10);\n"
        "    border-radius: 5px;\n"
        "    padding: 2px;\n"
        "}\n"
        "QLineEdit:hover{\n"
        "    border: 2px solid rgb(80,80,80);\n"
        "}\n"
        "QLineEdit:focus{\n"
        "    border: 2px solid rgb(80,80,80);\n"
        "}")
                self.lineEdit_model.setText("")
                self.lineEdit_model.setObjectName("lineEdit_model")
                self.lineEdit_plate = QtWidgets.QLineEdit(self.frame_vehicledata_plaintype__inside)
                self.lineEdit_plate.setGeometry(QtCore.QRect(10, 70, 261, 24))
                self.lineEdit_plate.setMaximumSize(QtCore.QSize(300, 16777211))
                self.lineEdit_plate.setStyleSheet("QLineEdit{\n"
        "    border: 2px solid rgb(10,10,10);\n"
        "    border-radius: 5px;\n"
        "    padding: 2px;\n"
        "}\n"
        "QLineEdit:hover{\n"
        "    border: 2px solid rgb(80,80,80);\n"
        "}\n"
        "QLineEdit:focus{\n"
        "    border: 2px solid rgb(80,80,80);\n"
        "}")
                self.lineEdit_plate.setText("")
                self.lineEdit_plate.setObjectName("lineEdit_plate")
                self.lineEdit_color = QtWidgets.QLineEdit(self.frame_vehicledata_plaintype__inside)
                self.lineEdit_color.setGeometry(QtCore.QRect(10, 100, 261, 24))
                self.lineEdit_color.setMaximumSize(QtCore.QSize(300, 16777211))
                self.lineEdit_color.setStyleSheet("QLineEdit{\n"
        "    border: 2px solid rgb(10,10,10);\n"
        "    border-radius: 5px;\n"
        "    padding: 2px;\n"
        "}\n"
        "QLineEdit:hover{\n"
        "    border: 2px solid rgb(80,80,80);\n"
        "}\n"
        "QLineEdit:focus{\n"
        "    border: 2px solid rgb(80,80,80);\n"
        "}")
                self.lineEdit_color.setText("")
                self.lineEdit_color.setObjectName("lineEdit_color")
                self.label_plaintype = QtWidgets.QLabel(self.frame_vehicledata_plaintype_outside)
                self.label_plaintype.setGeometry(QtCore.QRect(10, 220, 281, 51))
                font = QtGui.QFont()
                font.setFamily("Segoe UI")
                font.setBold(True)
                font.setWeight(75)
                self.label_plaintype.setFont(font)
                self.label_plaintype.setLayoutDirection(QtCore.Qt.LeftToRight)
                self.label_plaintype.setStyleSheet("QLabel{\n"
        "    border: 2px solid rgb(50,50,50);\n"
        "    border-radius: 5px;\n"
        "    \n"
        "    background-color: rgb(170, 255, 255);\n"
        "}")
                self.label_plaintype.setAlignment(QtCore.Qt.AlignCenter)
                self.label_plaintype.setObjectName("label_plaintype")
                self.frame_plaintype_inside = QtWidgets.QFrame(self.frame_vehicledata_plaintype_outside)
                self.frame_plaintype_inside.setGeometry(QtCore.QRect(10, 280, 281, 151))
                self.frame_plaintype_inside.setStyleSheet("QFrame{\n"
        "    border: 2px solid rgb(50,50,50);\n"
        "    border-radius: 5px;\n"
        "    \n"
        "    background-image: url(:/backgrounds/Images/background-blue-1715x980.jpg);\n"
        "}")
                self.frame_plaintype_inside.setFrameShape(QtWidgets.QFrame.StyledPanel)
                self.frame_plaintype_inside.setFrameShadow(QtWidgets.QFrame.Raised)
                self.frame_plaintype_inside.setObjectName("frame_plaintype_inside")
                self.radioButton_monitoring = QtWidgets.QRadioButton(self.frame_plaintype_inside)
                self.radioButton_monitoring.setGeometry(QtCore.QRect(11, 14, 19, 16))
                font = QtGui.QFont()
                font.setFamily("Segoe UI")
                font.setBold(False)
                font.setWeight(50)
                self.radioButton_monitoring.setFont(font)
                self.radioButton_monitoring.setStyleSheet("QRadioButton{\n"
        "    background-color: rgb(92, 230, 255);\n"
        "}\n"
        "QRadioButton:hover{\n"
        "    color: rgb(50,50,50);\n"
        "}")
                self.radioButton_monitoring.setText("")
                self.radioButton_monitoring.setObjectName("radioButton_monitoring")
                self.radioButton_bronze01 = QtWidgets.QRadioButton(self.frame_plaintype_inside)
                self.radioButton_bronze01.setGeometry(QtCore.QRect(11, 36, 19, 16))
                font = QtGui.QFont()
                font.setFamily("Segoe UI")
                self.radioButton_bronze01.setFont(font)
                self.radioButton_bronze01.setStyleSheet("QRadioButton{\n"
        "    background-color: rgb(92, 230, 255);\n"
        "}\n"
        "QRadioButton:hover{\n"
        "    color: rgb(50,50,50);\n"
        "}")
                self.radioButton_bronze01.setText("")
                self.radioButton_bronze01.setObjectName("radioButton_bronze01")
                self.radioButton_bronze02 = QtWidgets.QRadioButton(self.frame_plaintype_inside)
                self.radioButton_bronze02.setGeometry(QtCore.QRect(11, 58, 19, 16))
                font = QtGui.QFont()
                font.setFamily("Segoe UI")
                self.radioButton_bronze02.setFont(font)
                self.radioButton_bronze02.setStyleSheet("QRadioButton{\n"
        "    background-color: rgb(92, 230, 255);\n"
        "}\n"
        "QRadioButton:hover{\n"
        "    color: rgb(50,50,50);\n"
        "}")
                self.radioButton_bronze02.setText("")
                self.radioButton_bronze02.setObjectName("radioButton_bronze02")
                self.radioButton_silver01 = QtWidgets.QRadioButton(self.frame_plaintype_inside)
                self.radioButton_silver01.setGeometry(QtCore.QRect(11, 80, 19, 16))
                font = QtGui.QFont()
                font.setFamily("Segoe UI")
                self.radioButton_silver01.setFont(font)
                self.radioButton_silver01.setStyleSheet("QRadioButton{\n"
        "    background-color: rgb(92, 230, 255);\n"
        "}\n"
        "QRadioButton:hover{\n"
        "    color: rgb(50,50,50);\n"
        "}")
                self.radioButton_silver01.setText("")
                self.radioButton_silver01.setObjectName("radioButton_silver01")
                self.radioButton_silver02 = QtWidgets.QRadioButton(self.frame_plaintype_inside)
                self.radioButton_silver02.setGeometry(QtCore.QRect(11, 102, 19, 16))
                font = QtGui.QFont()
                font.setFamily("Segoe UI")
                self.radioButton_silver02.setFont(font)
                self.radioButton_silver02.setStyleSheet("QRadioButton{\n"
        "    background-color: rgb(92, 230, 255);\n"
        "}\n"
        "QRadioButton:hover{\n"
        "    color: rgb(50,50,50);\n"
        "}")
                self.radioButton_silver02.setText("")
                self.radioButton_silver02.setObjectName("radioButton_silver02")
                self.radioButton_gold = QtWidgets.QRadioButton(self.frame_plaintype_inside)
                self.radioButton_gold.setGeometry(QtCore.QRect(11, 124, 19, 16))
                font = QtGui.QFont()
                font.setFamily("Segoe UI")
                self.radioButton_gold.setFont(font)
                self.radioButton_gold.setStyleSheet("QRadioButton{\n"
        "    background-color: rgb(92, 230, 255);\n"
        "}\n"
        "QRadioButton:hover{\n"
        "    color: rgb(50,50,50);\n"
        "}")
                self.radioButton_gold.setText("")
                self.radioButton_gold.setObjectName("radioButton_gold")
                self.label_monitoring = QtWidgets.QLabel(self.frame_plaintype_inside)
                self.label_monitoring.setGeometry(QtCore.QRect(30, 14, 171, 16))
                font = QtGui.QFont()
                font.setFamily("Segoe UI")
                self.label_monitoring.setFont(font)
                self.label_monitoring.setStyleSheet("QLabel{\n"
        "    border: no-border;\n"
        "}\n"
        "QLabel:hover{\n"
        "    color: rgb(50,50,50);\n"
        "}")
                self.label_monitoring.setObjectName("label_monitoring")
                self.label_bronze01 = QtWidgets.QLabel(self.frame_plaintype_inside)
                self.label_bronze01.setGeometry(QtCore.QRect(30, 36, 161, 16))
                font = QtGui.QFont()
                font.setFamily("Segoe UI")
                self.label_bronze01.setFont(font)
                self.label_bronze01.setStyleSheet("QLabel{\n"
        "    border: no-border;\n"
        "}\n"
        "QLabel:hover{\n"
        "    color: rgb(50,50,50);\n"
        "}")
                self.label_bronze01.setObjectName("label_bronze01")
                self.label_bronze02 = QtWidgets.QLabel(self.frame_plaintype_inside)
                self.label_bronze02.setGeometry(QtCore.QRect(30, 58, 161, 16))
                font = QtGui.QFont()
                font.setFamily("Segoe UI")
                self.label_bronze02.setFont(font)
                self.label_bronze02.setStyleSheet("QLabel{\n"
        "    border: no-border;\n"
        "}\n"
        "QLabel:hover{\n"
        "    color: rgb(50,50,50);\n"
        "}")
                self.label_bronze02.setObjectName("label_bronze02")
                self.label_silver01 = QtWidgets.QLabel(self.frame_plaintype_inside)
                self.label_silver01.setGeometry(QtCore.QRect(30, 80, 161, 16))
                font = QtGui.QFont()
                font.setFamily("Segoe UI")
                self.label_silver01.setFont(font)
                self.label_silver01.setStyleSheet("QLabel{\n"
        "    border: no-border;\n"
        "}\n"
        "QLabel:hover{\n"
        "    color: rgb(50,50,50);\n"
        "}")
                self.label_silver01.setObjectName("label_silver01")
                self.label_silver02 = QtWidgets.QLabel(self.frame_plaintype_inside)
                self.label_silver02.setGeometry(QtCore.QRect(30, 102, 161, 16))
                font = QtGui.QFont()
                font.setFamily("Segoe UI")
                self.label_silver02.setFont(font)
                self.label_silver02.setStyleSheet("QLabel{\n"
        "    border: no-border;\n"
        "}\n"
        "QLabel:hover{\n"
        "    color: rgb(50,50,50);\n"
        "}")
                self.label_silver02.setObjectName("label_silver02")
                self.label_gold = QtWidgets.QLabel(self.frame_plaintype_inside)
                self.label_gold.setGeometry(QtCore.QRect(30, 124, 161, 16))
                font = QtGui.QFont()
                font.setFamily("Segoe UI")
                self.label_gold.setFont(font)
                self.label_gold.setStyleSheet("QLabel{\n"
        "    border: no-border;\n"
        "}\n"
        "QLabel:hover{\n"
        "    color: rgb(50,50,50);\n"
        "}")
                self.label_gold.setObjectName("label_gold")
                self.frame_coverages = QtWidgets.QFrame(self.frame_background)
                self.frame_coverages.setGeometry(QtCore.QRect(470, 1, 300, 703))
                self.frame_coverages.setMinimumSize(QtCore.QSize(0, 0))
                self.frame_coverages.setMaximumSize(QtCore.QSize(300, 1000))
                self.frame_coverages.setStyleSheet("border: no-border;\n"
        "background-image: url(:/backgrounds/Images/background-blue-1715x980.jpg);")
                self.frame_coverages.setFrameShape(QtWidgets.QFrame.StyledPanel)
                self.frame_coverages.setFrameShadow(QtWidgets.QFrame.Raised)
                self.frame_coverages.setObjectName("frame_coverages")
                self.label_plains = QtWidgets.QLabel(self.frame_coverages)
                self.label_plains.setGeometry(QtCore.QRect(10, 10, 281, 51))
                font = QtGui.QFont()
                font.setFamily("Segoe UI")
                font.setBold(True)
                font.setWeight(75)
                self.label_plains.setFont(font)
                self.label_plains.setLayoutDirection(QtCore.Qt.LeftToRight)
                self.label_plains.setStyleSheet("QLabel{\n"
        "    border: 2px solid rgb(50,50,50);\n"
        "    border-radius: 5px;\n"
        "    \n"
        "    background-image: url(:/backgrounds/Images/background-blue-1715x980.jpg);\n"
        "}")
                self.label_plains.setAlignment(QtCore.Qt.AlignCenter)
                self.label_plains.setObjectName("label_plains")
                self.frame_checkboxes = QtWidgets.QFrame(self.frame_coverages)
                self.frame_checkboxes.setGeometry(QtCore.QRect(10, 70, 281, 581))
                self.frame_checkboxes.setStyleSheet("QFrame{\n"
        "    border: 2px solid rgb(50,50,50);\n"
        "    border-radius: 5px;\n"
        "    background-image: url(:/backgrounds/Images/background-blue-1715x980.jpg);\n"
        "}")
                self.frame_checkboxes.setFrameShape(QtWidgets.QFrame.StyledPanel)
                self.frame_checkboxes.setFrameShadow(QtWidgets.QFrame.Raised)
                self.frame_checkboxes.setObjectName("frame_checkboxes")
                self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_checkboxes)
                self.verticalLayout_2.setObjectName("verticalLayout_2")
                self.checkBox_monitoring = QtWidgets.QCheckBox(self.frame_checkboxes)
                self.checkBox_monitoring.setStyleSheet("QCheckBox{\n"
        "    background-color: rgb(92, 230, 255);\n"
        "}\n"
        "QCheckBox:hover{\n"
        "    color: rgb(50,50,50);\n"
        "}")
                self.checkBox_monitoring.setObjectName("checkBox_monitoring")
                self.verticalLayout_2.addWidget(self.checkBox_monitoring)
                self.checkBox_robbery = QtWidgets.QCheckBox(self.frame_checkboxes)
                self.checkBox_robbery.setStyleSheet("QCheckBox{\n"
        "    background-color: rgb(92, 230, 255);\n"
        "}\n"
        "QCheckBox:hover{\n"
        "    color: rgb(50,50,50);\n"
        "}")
                self.checkBox_robbery.setObjectName("checkBox_robbery")
                self.verticalLayout_2.addWidget(self.checkBox_robbery)
                self.checkBox_theft = QtWidgets.QCheckBox(self.frame_checkboxes)
                self.checkBox_theft.setStyleSheet("QCheckBox{\n"
        "    background-color: rgb(92, 230, 255);\n"
        "}\n"
        "QCheckBox:hover{\n"
        "    color: rgb(50,50,50);\n"
        "}")
                self.checkBox_theft.setObjectName("checkBox_theft")
                self.verticalLayout_2.addWidget(self.checkBox_theft)
                self.checkBox_collision = QtWidgets.QCheckBox(self.frame_checkboxes)
                self.checkBox_collision.setStyleSheet("QCheckBox{\n"
        "    background-color: rgb(92, 230, 255);\n"
        "}\n"
        "QCheckBox:hover{\n"
        "    color: rgb(50,50,50);\n"
        "}")
                self.checkBox_collision.setObjectName("checkBox_collision")
                self.verticalLayout_2.addWidget(self.checkBox_collision)
                self.checkBox_pt = QtWidgets.QCheckBox(self.frame_checkboxes)
                self.checkBox_pt.setStyleSheet("QCheckBox{\n"
        "    background-color: rgb(92, 230, 255);\n"
        "}\n"
        "QCheckBox:hover{\n"
        "    color: rgb(50,50,50);\n"
        "}")
                self.checkBox_pt.setObjectName("checkBox_pt")
                self.verticalLayout_2.addWidget(self.checkBox_pt)
                self.checkBox_3R = QtWidgets.QCheckBox(self.frame_checkboxes)
                self.checkBox_3R.setStyleSheet("QCheckBox{\n"
        "    background-color: rgb(92, 230, 255);\n"
        "}\n"
        "QCheckBox:hover{\n"
        "    color: rgb(50,50,50);\n"
        "}")
                self.checkBox_3R.setObjectName("checkBox_3R")
                self.verticalLayout_2.addWidget(self.checkBox_3R)
                self.checkBox_6R = QtWidgets.QCheckBox(self.frame_checkboxes)
                self.checkBox_6R.setStyleSheet("QCheckBox{\n"
        "    background-color: rgb(92, 230, 255);\n"
        "}\n"
        "QCheckBox:hover{\n"
        "    color: rgb(50,50,50);\n"
        "}")
                self.checkBox_6R.setObjectName("checkBox_6R")
                self.verticalLayout_2.addWidget(self.checkBox_6R)
                self.checkBox_RUnlimited = QtWidgets.QCheckBox(self.frame_checkboxes)
                self.checkBox_RUnlimited.setStyleSheet("QCheckBox{\n"
        "    background-color: rgb(92, 230, 255);\n"
        "}\n"
        "QCheckBox:hover{\n"
        "    color: rgb(50,50,50);\n"
        "}")
                self.checkBox_RUnlimited.setObjectName("checkBox_RUnlimited")
                self.verticalLayout_2.addWidget(self.checkBox_RUnlimited)
                self.checkBox_R500 = QtWidgets.QCheckBox(self.frame_checkboxes)
                self.checkBox_R500.setStyleSheet("QCheckBox{\n"
        "    background-color: rgb(92, 230, 255);\n"
        "}\n"
        "QCheckBox:hover{\n"
        "    color: rgb(50,50,50);\n"
        "}")
                self.checkBox_R500.setObjectName("checkBox_R500")
                self.verticalLayout_2.addWidget(self.checkBox_R500)
                self.checkBox_glasses = QtWidgets.QCheckBox(self.frame_checkboxes)
                self.checkBox_glasses.setStyleSheet("QCheckBox{\n"
        "    background-color: rgb(92, 230, 255);\n"
        "}\n"
        "QCheckBox:hover{\n"
        "    color: rgb(50,50,50);\n"
        "}")
                self.checkBox_glasses.setObjectName("checkBox_glasses")
                self.verticalLayout_2.addWidget(self.checkBox_glasses)
                self.checkBox_others = QtWidgets.QCheckBox(self.frame_checkboxes)
                self.checkBox_others.setStyleSheet("QCheckBox{\n"
        "    background-color: rgb(92, 230, 255);\n"
        "}\n"
        "QCheckBox:hover{\n"
        "    color: rgb(50,50,50);\n"
        "}")
                self.checkBox_others.setObjectName("checkBox_others")
                self.verticalLayout_2.addWidget(self.checkBox_others)
                self.verticalLayout.addWidget(self.frame_background)
                self.frame_statusbarrier = QtWidgets.QFrame(self.centralwidget)
                self.frame_statusbarrier.setMaximumSize(QtCore.QSize(16777215, 33))
                self.frame_statusbarrier.setStyleSheet("background-color: rgb(0, 0, 255);")
                self.frame_statusbarrier.setFrameShape(QtWidgets.QFrame.StyledPanel)
                self.frame_statusbarrier.setFrameShadow(QtWidgets.QFrame.Raised)
                self.frame_statusbarrier.setObjectName("frame_statusbarrier")
                self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_statusbarrier)
                self.horizontalLayout.setObjectName("horizontalLayout")
                self.label = QtWidgets.QLabel(self.frame_statusbarrier)
                self.label.setMaximumSize(QtCore.QSize(16777215, 16777215))
                font = QtGui.QFont()
                font.setFamily("Segoe UI")
                font.setBold(True)
                font.setItalic(True)
                font.setWeight(75)
                self.label.setFont(font)
                self.label.setStyleSheet("color: rgb(181, 198, 186);")
                self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
                self.label.setObjectName("label")
                self.horizontalLayout.addWidget(self.label)
                self.verticalLayout.addWidget(self.frame_statusbarrier)
                MainWindow.setCentralWidget(self.centralwidget)
                self.toolBar = QtWidgets.QToolBar(MainWindow)
                self.toolBar.setObjectName("toolBar")
                MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
                self.actionGerar_termo_de_ades_o = QtWidgets.QAction(MainWindow)
                self.actionGerar_termo_de_ades_o.setObjectName("actionGerar_termo_de_ades_o")
                self.actionNovo = QtWidgets.QAction(MainWindow)
                self.actionNovo.setObjectName("actionNovo")
                self.actionSalvar = QtWidgets.QAction(MainWindow)
                self.actionSalvar.setObjectName("actionSalvar")

                #
                #FUNCTIONS
                #

                self.pushButton_generateterm.clicked.connect(self.GenerateTermInPDF)

                self.retranslateUi(MainWindow)
                QtCore.QMetaObject.connectSlotsByName(MainWindow)

        def retranslateUi(self, MainWindow):
                _translate = QtCore.QCoreApplication.translate
                MainWindow.setWindowTitle(_translate("MainWindow", "MRS Veicular"))
                self.label_2.setText(_translate("MainWindow", "PMS - Policyholder Management System"))
                self.label_3.setText(_translate("MainWindow", "Sistema de Gestão de Segurados"))
                self.pushButton_generateterm.setText(_translate("MainWindow", "Gerar Termo de Adesão"))
                self.pushButton_printterm.setText(_translate("MainWindow", "Imprimir Termo de Adesão"))
                self.label_clientdata.setText(_translate("MainWindow", "DADOS DO ASSOCIADO"))
                self.lineEdit_name.setPlaceholderText(_translate("MainWindow", "NOME"))
                self.lineEdit_cpf.setPlaceholderText(_translate("MainWindow", "CPF"))
                self.lineEdit_rg.setPlaceholderText(_translate("MainWindow", "RG"))
                self.lineEdit_phone.setPlaceholderText(_translate("MainWindow", "TELEFONE"))
                self.label_vehicle.setText(_translate("MainWindow", "VEÍCULO"))
                self.lineEdit_assembler.setPlaceholderText(_translate("MainWindow", "MONTADORA"))
                self.lineEdit_model.setPlaceholderText(_translate("MainWindow", "MODELO"))
                self.lineEdit_plate.setPlaceholderText(_translate("MainWindow", "PLACA"))
                self.lineEdit_color.setPlaceholderText(_translate("MainWindow", "COR"))
                self.label_plaintype.setText(_translate("MainWindow", "TIPO DE PLANO"))
                self.label_monitoring.setText(_translate("MainWindow", "Monitoramento e Rastreamento"))
                self.label_bronze01.setText(_translate("MainWindow", "Bronze - 01"))
                self.label_bronze02.setText(_translate("MainWindow", "Bronze - 02"))
                self.label_silver01.setText(_translate("MainWindow", "Prata - 01"))
                self.label_silver02.setText(_translate("MainWindow", "Prata - 02"))
                self.label_gold.setText(_translate("MainWindow", "Ouro"))
                self.label_plains.setText(_translate("MainWindow", "COBERTURAS"))
                self.checkBox_monitoring.setText(_translate("MainWindow", "Monitoramento"))
                self.checkBox_robbery.setText(_translate("MainWindow", "Roubo"))
                self.checkBox_theft.setText(_translate("MainWindow", "Furto"))
                self.checkBox_collision.setText(_translate("MainWindow", "Colisão"))
                self.checkBox_pt.setText(_translate("MainWindow", "Perda Total"))
                self.checkBox_3R.setText(_translate("MainWindow", "3 Reboques Gratuitos a.a."))
                self.checkBox_6R.setText(_translate("MainWindow", "6 Reboques Gratuitos a.a"))
                self.checkBox_RUnlimited.setText(_translate("MainWindow", "Reboque Ilimitado"))
                self.checkBox_R500.setText(_translate("MainWindow", "500 Km de Reboque"))
                self.checkBox_glasses.setText(_translate("MainWindow", "Vidros em Geral"))
                self.checkBox_others.setText(_translate("MainWindow", "Terceiros"))
                self.label.setText(_translate("MainWindow", "Created by Sérgio Lima - V2.0"))
                self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
                self.actionGerar_termo_de_ades_o.setText(_translate("MainWindow", "Gerar termo de adesão"))
                self.actionNovo.setText(_translate("MainWindow", "Novo..."))
                self.actionSalvar.setText(_translate("MainWindow", "Salvar"))
        import file_rcV3


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
