# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'TestedeEntrada.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from reportlab.pdfgen import canvas
from reportlab.lib.pagesizes import A4


class Ui_MainWindow(object):

    def GenerateTermInPDF(self):
        valor = str(self.textEdit_nome)
        print(valor)
        
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(300, 300)
        MainWindow.setMinimumSize(QtCore.QSize(300, 300))
        MainWindow.setMaximumSize(QtCore.QSize(300, 300))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.textEdit_nome = QtWidgets.QLineEdit(self.centralwidget)
        self.textEdit_nome.setGeometry(QtCore.QRect(50, 10, 200, 23))
        self.textEdit_nome.setObjectName("textEdit_nome")
        self.pushButton_generatepdf = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_generatepdf.setGeometry(QtCore.QRect(110, 40, 75, 23))
        self.pushButton_generatepdf.setObjectName("pushButton_generatepdf")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 300, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.pushButton_generatepdf.clicked.connect(self.GenerateTermInPDF)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Teste de Entrada"))
        self.textEdit_nome.setPlaceholderText(_translate("MainWindow", "NOME"))
        self.pushButton_generatepdf.setText(_translate("MainWindow", "Mostrar nome"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
