# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'TestedeEntrada.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from reportlab.pdfgen import canvas
from reportlab.lib.pagesizes import A4


class Ui_MainWindow(object):

    def GeneratePDF(self):
        if self.radioButton_sergio.isChecked():
            self.cnv = canvas.Canvas('Teste de Entrada.pdf')
            self.cnv.drawString(x=250, y=700,text=self.label_sergio.text(), mode=1)
            self.cnv.save()

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(300, 300)
        MainWindow.setMinimumSize(QtCore.QSize(300, 300))
        MainWindow.setMaximumSize(QtCore.QSize(300, 300))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton_generatepdf = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_generatepdf.setGeometry(QtCore.QRect(110, 90, 75, 23))
        self.pushButton_generatepdf.setObjectName("pushButton_generatepdf")
        self.radioButton_sergio = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_sergio.setGeometry(QtCore.QRect(80, 20, 82, 17))
        self.radioButton_sergio.setText("")
        self.radioButton_sergio.setObjectName("radioButton_sergio")
        self.radioButton_samara = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_samara.setGeometry(QtCore.QRect(80, 40, 82, 17))
        self.radioButton_samara.setText("")
        self.radioButton_samara.setObjectName("radioButton_samara")
        self.radioButton_sandro = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_sandro.setGeometry(QtCore.QRect(80, 60, 82, 17))
        self.radioButton_sandro.setText("")
        self.radioButton_sandro.setObjectName("radioButton_sandro")
        self.label_sergio = QtWidgets.QLabel(self.centralwidget)
        self.label_sergio.setGeometry(QtCore.QRect(100, 20, 47, 13))
        self.label_sergio.setObjectName("label_sergio")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(100, 40, 47, 13))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(100, 60, 47, 13))
        self.label_2.setObjectName("label_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 300, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.pushButton_generatepdf.clicked.connect(self.GeneratePDF)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Teste de Entrada"))
        self.pushButton_generatepdf.setText(_translate("MainWindow", "Gerar PDF"))
        self.label_sergio.setText(_translate("MainWindow", "SERGIO"))
        self.label.setText(_translate("MainWindow", "SAMARA"))
        self.label_2.setText(_translate("MainWindow", "SANDRO"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
