# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main-window.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from adhesion import Ui_Adesao_MainWindow


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(600, 600)
        MainWindow.setMaximumSize(QtCore.QSize(600, 600))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setMinimumSize(QtCore.QSize(0, 0))
        self.centralwidget.setMaximumSize(QtCore.QSize(600, 600))
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.scrollAreaMain = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollAreaMain.setMaximumSize(QtCore.QSize(600, 600))
        self.scrollAreaMain.setStyleSheet("background-color: rgb(85, 170, 255);\n"
"")
        self.scrollAreaMain.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.scrollAreaMain.setWidgetResizable(True)
        self.scrollAreaMain.setObjectName("scrollAreaMain")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 600, 600))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frameLogo = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.frameLogo.setStyleSheet("QFrame{\n"
"    image: url(:/Logo/logo.png);\n"
"    background-repeat: no-repeat;\n"
"}\n"
"\n"
"\n"
"")
        self.frameLogo.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frameLogo.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameLogo.setObjectName("frameLogo")
        self.verticalLayout_2.addWidget(self.frameLogo)
        self.frameMenus = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.frameMenus.setStyleSheet("")
        self.frameMenus.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameMenus.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameMenus.setObjectName("frameMenus")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frameMenus)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frameButton3 = QtWidgets.QFrame(self.frameMenus)
        self.frameButton3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameButton3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameButton3.setObjectName("frameButton3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frameButton3)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.pushButton = QtWidgets.QPushButton(self.frameButton3)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout_3.addWidget(self.pushButton)
        self.horizontalLayout.addWidget(self.frameButton3)
        self.frameButton2 = QtWidgets.QFrame(self.frameMenus)
        self.frameButton2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameButton2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameButton2.setObjectName("frameButton2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frameButton2)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout.addWidget(self.frameButton2)
        self.frameButton1 = QtWidgets.QFrame(self.frameMenus)
        self.frameButton1.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameButton1.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameButton1.setObjectName("frameButton1")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frameButton1)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout.addWidget(self.frameButton1)
        self.verticalLayout_2.addWidget(self.frameMenus)
        self.scrollAreaMain.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.scrollAreaMain)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.pushButton.clicked.connect(self.criarTermoAdesao)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Sistema Gerador de Termos"))
        self.pushButton.setText(_translate("MainWindow", "ADESÃO"))

    def criarTermoAdesao(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_Adesao_MainWindow()
        self.ui.setupUi(self.window)
        self.window.show()

    import file_rc_main_window


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())